// banking_api_ui/src/components/education/GatewayPolicySplitPanel.js
import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
import EducationDrawer from '../shared/EducationDrawer';
import { GATEWAY_ENFORCEMENT_JOURNEY_MERMAID, GATEWAY_ENFORCEMENT_STAKES, GATEWAY_ENFORCEMENT_ROWS } from './gatewayEnforcementDiagram.generated';

const STATUS_LABEL = {
  done: '✅ enforced',
  bydesign: '✅ P1AZ owns the decision',
  flagged: '✅ built · opt-in flag',
  pending: 'planned — P1AZ covers it today',
};

const VERDICT_STYLE = {
  done: { bg: '#0a2418', fg: '#6ee7b7', border: '#059669', icon: '✅' },
  bydesign: { bg: '#062b2b', fg: '#5eead4', border: '#0d9488', icon: '✅' },
  flagged: { bg: '#2a1a00', fg: '#fbbf24', border: '#d97706', icon: '✅' },
  pending: { bg: '#2d0a0a', fg: '#fca5a5', border: '#dc2626', icon: '⚠️' },
};

/** Renders the generated Mermaid source once on mount. Static, not live-trace —
 *  the diagram itself is regenerated by re-running the script, not by this
 *  component polling anything. */
function EnforcementMapDiagram() {
  const containerRef = useRef(null);
  const [renderError, setRenderError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    setRenderError(null);
    mermaid.initialize({
      startOnLoad: false,
      theme: 'default',
      securityLevel: 'loose',
      themeVariables: { fontSize: '20px' },
      flowchart: { htmlLabels: true, useMaxWidth: true, curve: 'basis' },
    });
    (async () => {
      try {
        const { svg } = await mermaid.render('gw-enforcement-map-svg', GATEWAY_ENFORCEMENT_JOURNEY_MERMAID);
        if (!cancelled && containerRef.current) containerRef.current.innerHTML = svg;
      } catch (err) {
        if (!cancelled) setRenderError(err?.message || 'Mermaid render failed');
      }
    })();
    return () => { cancelled = true; };
  }, []);

  return renderError ? (
    <div style={{ padding: 12, color: '#dc2626', fontSize: 12 }}>
      Render error: {renderError}
    </div>
  ) : (
    <div ref={containerRef} role="img" aria-label="Gateway enforcement map" style={{ overflow: 'auto' }} />
  );
}

export default function GatewayPolicySplitPanel({ isOpen, onClose, initialTabId }) {
  const tabs = [
    {
      id: 'overview',
      label: 'Coarse vs fine',
      content: (
        <>
          <h3 style={{ marginTop: 0 }}>Two enforcement points, two jobs</h3>
          <p>
            This demo has two authorization layers on every agent tool call: the <strong>Agent Gateway</strong>
            {' '}(a PEP — Policy Enforcement Point, either PingOne Agent Gateway/IG or the Node demo gateway) and{' '}
            <strong>PingOne Authorize</strong> (P1AZ, the PDP — Policy Decision Point). They are deliberately
            split by grain, not duplicated:
          </p>
          <table className="edu-table">
            <thead>
              <tr><th>Question</th><th>Who decides</th></tr>
            </thead>
            <tbody>
              <tr><td>Is the token real, live, mine? (authentication)</td><td>Gateway</td></tr>
              <tr><td>Coarse access — scope, audience, anti-bypass</td><td>Gateway locally <em>and</em> the PDP (see below)</td></tr>
              <tr><td>Business policy — amount, tier, group, step-up, HITL</td><td>PingOne Authorize (P1AZ)</td></tr>
            </tbody>
          </table>
          <div className="edu-info-box">
            The gateway does not re-implement P1AZ's business rules. Five checks do land on the gateway, because
            they need the raw token claims and call parameters the PEP holds — set membership over scopes, groups
            and payees, epoch-second timestamps, the full multi-valued <code>aud</code>. The PDP gets scalars; the
            PEP has the originals, so it owns those five. That's what this page covers.
          </div>
        </>
      ),
    },
    {
      id: 'why-p1az-cant',
      label: 'Why the gateway owns it',
      content: (
        <>
          <h3 style={{ marginTop: 0 }}>5 checks the PEP owns</h3>
          <p>
            The cloud policy is a snapshot import, and its DSL compares attribute to attribute: scalars, string
            types, no set membership. The BFF and gateway flatten what they can into scalars for the PDP —{' '}
            <code>UserTier</code>, <code>InRequiredGroup</code>, <code>TokenKidKnown</code>. These five keep their
            original shape (sets, arrays, epoch numbers), so the PEP is where they get checked:
          </p>
          {GATEWAY_ENFORCEMENT_ROWS.map((row) => (
            <div key={row.id} className="edu-info-box" style={{ marginBottom: 10 }}>
              <strong>{row.label}</strong>
              <p style={{ margin: '4px 0 0' }}>{row.p1az}</p>
            </div>
          ))}
        </>
      ),
    },
    {
      id: 'enforcement-map',
      label: 'Enforcement map',
      content: (
        <>
          <h3 style={{ marginTop: 0 }}>Where each check is enforced today</h3>
          <p>
            Generated from the actual source — not hand-maintained. Re-running{' '}
            <code>node scripts/gen-gateway-enforcement-map.js</code> after a code change updates this diagram
            and <code>docs/gateway-enforcement-map.md</code> together, from the same scan.
          </p>
          <p style={{ fontSize: 13, opacity: 0.8 }}>
            <strong>Reading the diagram:</strong> P1AZ decides business policy — amount, tier,
            group, step-up, HITL. These 5 checks run at the PEP, where the raw token claims and
            call parameters live. Each branches to the gateway that enforces it, then reconverges
            on one decision. Box color shows which gateway carries it.
          </p>
          <EnforcementMapDiagram />
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12, marginTop: 16 }}>
            {GATEWAY_ENFORCEMENT_STAKES.map((s) => {
              const style = VERDICT_STYLE[s.verdictTier];
              return (
                <div key={s.id} style={{ border: '1px solid var(--th-border)', borderRadius: 8, padding: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  <div style={{ fontSize: 13, fontWeight: 600 }}>{s.label}</div>
                  <div style={{ fontSize: 11.5, opacity: 0.75, fontStyle: 'italic', lineHeight: 1.4 }}>{s.scenario}</div>
                  <div style={{ fontSize: 11, padding: '5px 8px', borderRadius: 5, background: style.bg, color: style.fg, border: `1px solid ${style.border}` }}>
                    {style.icon} {s.verdictText}
                  </div>
                </div>
              );
            })}
          </div>
          <table className="edu-table" style={{ marginTop: 16 }}>
            <thead>
              <tr><th>Check</th><th>Node gateway</th><th>IG gateway (groovy)</th></tr>
            </thead>
            <tbody>
              {GATEWAY_ENFORCEMENT_ROWS.map((row) => (
                <tr key={row.id}>
                  <td>{row.label}</td>
                  <td>{STATUS_LABEL[row.node.status]}</td>
                  <td>{STATUS_LABEL[row.groovy.status]}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="edu-info-box" style={{ marginTop: 12 }}>
            On the IG groovy path, P1AZ owns the RAR decision: the filter forwards{' '}
            <code>RarAuthorizationDetails</code>, <code>RarMaxAmount</code> and{' '}
            <code>RarPermittedPayees</code>, and the cloud <code>RarMaxAmount</code> rule decides — which is why{' '}
            <code>ping-gateway/scripts/check-groovy-params.sh</code> warns against a local DENY there ("P1AZ
            decides"). A local payee DENY is available behind <code>PG_LOCAL_RAR_PAYEE_ENFORCE</code> for the
            belt-and-braces variant. Separately, <code>ff_rar</code> itself is opt-in because PingOne SaaS accepts{' '}
            <code>authorization_details</code> on PAR only, so the BFF carries the grant in the TraT{' '}
            <code>azd</code> envelope; it is minted natively on AIC / PingFederate 11.2+.
          </div>
        </>
      ),
    },
    {
      id: 'inrepo',
      label: 'In this repo',
      content: (
        <>
          <h3 style={{ marginTop: 0 }}>Key files</h3>
          <ul>
            <li><code>snapshots/gen-authorize-snapshot.js</code> — the reconciler that keeps the cloud P1AZ snapshot in sync with <code>scope-topology.json</code>; its header comment is the authoritative list of what's deliberately not modeled in the cloud policy.</li>
            <li><code>demo_mcp_gateway/src/auth/GatewayTokenPolicy.ts</code> — Node gateway's D-05 anti-bypass check, unconditional on every inbound token.</li>
            <li><code>demo_mcp_gateway/src/rarEnforce.ts</code> — Node gateway's RAR payee/amount subset check.</li>
            <li><code>ping-gateway/scripts/groovy/p1az-decision.groovy</code> — the IG gateway's policy-decision filter; builds and forwards the same parameters the Node gateway does to the same PDP.</li>
            <li><code>docs/authorization-decision-split.md</code> — full engineering audit of the split (file:line citations, decision-order trace, what's right and what's not).</li>
            <li><code>docs/gateway-enforcement-map.md</code> — this page's generated source doc.</li>
          </ul>
        </>
      ),
    },
  ];

  return (
    <EducationDrawer
      isOpen={isOpen}
      onClose={onClose}
      title="Gateway vs P1AZ — the decision split"
      subtitle="Which enforcement point owns which decision, and where each check runs"
      tabs={tabs}
      initialTabId={initialTabId || 'overview'}
      width="min(720px, 100vw)"
    />
  );
}
