// banking_api_ui/src/components/education/GatewayPolicySplitPanel.js
import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
import EducationDrawer from '../shared/EducationDrawer';
import { GATEWAY_ENFORCEMENT_MERMAID, GATEWAY_ENFORCEMENT_ROWS } from './gatewayEnforcementDiagram.generated';

const STATUS_LABEL = {
  done: '✅ enforced',
  flagged: '⚠️ built, default OFF',
  pending: '❌ gap',
};

/** Renders the generated Mermaid source once on mount. Static, not live-trace —
 *  the diagram itself is regenerated by re-running the script, not by this
 *  component polling anything. */
function EnforcementMapDiagram() {
  const containerRef = useRef(null);
  const [renderError, setRenderError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    setRenderError(null);
    mermaid.initialize({
      startOnLoad: false,
      theme: 'default',
      securityLevel: 'loose',
      flowchart: { htmlLabels: true, useMaxWidth: true, curve: 'basis' },
    });
    (async () => {
      try {
        const { svg } = await mermaid.render('gw-enforcement-map-svg', GATEWAY_ENFORCEMENT_MERMAID);
        if (!cancelled && containerRef.current) containerRef.current.innerHTML = svg;
      } catch (err) {
        if (!cancelled) setRenderError(err?.message || 'Mermaid render failed');
      }
    })();
    return () => { cancelled = true; };
  }, []);

  return renderError ? (
    <div style={{ padding: 12, color: '#dc2626', fontSize: 12 }}>
      Render error: {renderError}
    </div>
  ) : (
    <div ref={containerRef} role="img" aria-label="Gateway enforcement map" style={{ overflow: 'auto' }} />
  );
}

export default function GatewayPolicySplitPanel({ isOpen, onClose, initialTabId }) {
  const tabs = [
    {
      id: 'overview',
      label: 'Coarse vs fine',
      content: (
        <>
          <h3 style={{ marginTop: 0 }}>Two enforcement points, two jobs</h3>
          <p>
            This demo has two authorization layers on every agent tool call: the <strong>Agent Gateway</strong>
            {' '}(a PEP — Policy Enforcement Point, either PingGateway/IG or the Node demo gateway) and{' '}
            <strong>PingOne Authorize</strong> (P1AZ, the PDP — Policy Decision Point). They are deliberately
            split by grain, not duplicated:
          </p>
          <table className="edu-table">
            <thead>
              <tr><th>Question</th><th>Who decides</th></tr>
            </thead>
            <tbody>
              <tr><td>Is the token real, live, mine? (authentication)</td><td>Gateway</td></tr>
              <tr><td>Coarse access — scope, audience, anti-bypass</td><td>Gateway locally <em>and</em> the PDP (see below)</td></tr>
              <tr><td>Business policy — amount, tier, group, step-up, HITL</td><td>PingOne Authorize (P1AZ)</td></tr>
            </tbody>
          </table>
          <div className="edu-info-box">
            The gateway is not supposed to re-implement P1AZ's business rules. But P1AZ's decision DSL has real
            structural limits — it cannot express 5 specific rules a full authorization posture needs. Those 5
            fall back to the gateway as a local backstop. That's what this page covers.
          </div>
        </>
      ),
    },
    {
      id: 'why-p1az-cant',
      label: "Why P1AZ can't",
      content: (
        <>
          <h3 style={{ marginTop: 0 }}>5 rules the cloud PDP's DSL cannot express</h3>
          <p>
            PingOne Authorize has no policy API for COMPARISON conditions — the cloud policy is a snapshot
            import, and its DSL is attribute-to-attribute comparison only: no set/contains operator, no array
            membership, string types only for what it receives. That ceiling is real, not a bug:
          </p>
          {GATEWAY_ENFORCEMENT_ROWS.map((row) => (
            <div key={row.id} className="edu-info-box" style={{ marginBottom: 10 }}>
              <strong>{row.label}</strong>
              <p style={{ margin: '4px 0 0' }}>{row.p1az}</p>
            </div>
          ))}
        </>
      ),
    },
    {
      id: 'enforcement-map',
      label: 'Enforcement map',
      content: (
        <>
          <h3 style={{ marginTop: 0 }}>Where each rule is enforced today</h3>
          <p>
            Generated from the actual source — not hand-maintained. Re-running{' '}
            <code>node scripts/gen-gateway-enforcement-map.js</code> after a code change updates this diagram
            and <code>docs/gateway-enforcement-map.md</code> together, from the same scan.
          </p>
          <EnforcementMapDiagram />
          <table className="edu-table" style={{ marginTop: 16 }}>
            <thead>
              <tr><th>Rule</th><th>Node gateway</th><th>IG gateway (groovy)</th></tr>
            </thead>
            <tbody>
              {GATEWAY_ENFORCEMENT_ROWS.map((row) => (
                <tr key={row.id}>
                  <td>{row.label}</td>
                  <td>{STATUS_LABEL[row.node.status]}</td>
                  <td>{STATUS_LABEL[row.groovy.status]}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="edu-info-box" style={{ marginTop: 12 }}>
            RAR payee is deliberately <strong>not</strong> auto-enabled on the IG groovy path even once built —
            the repo's own <code>ping-gateway/scripts/check-groovy-params.sh</code> warns against a local RAR
            DENY there ("P1AZ decides"). It ships behind <code>PG_LOCAL_RAR_PAYEE_ENFORCE</code>, default off.
          </div>
        </>
      ),
    },
    {
      id: 'inrepo',
      label: 'In this repo',
      content: (
        <>
          <h3 style={{ marginTop: 0 }}>Key files</h3>
          <ul>
            <li><code>snapshots/gen-authorize-snapshot.js</code> — the reconciler that keeps the cloud P1AZ snapshot in sync with <code>scope-topology.json</code>; its header comment is the authoritative list of what's deliberately not modeled in the cloud policy.</li>
            <li><code>demo_mcp_gateway/src/auth/GatewayTokenPolicy.ts</code> — Node gateway's D-05 anti-bypass check, unconditional on every inbound token.</li>
            <li><code>demo_mcp_gateway/src/rarEnforce.ts</code> — Node gateway's RAR payee/amount subset check.</li>
            <li><code>ping-gateway/scripts/groovy/p1az-decision.groovy</code> — the IG gateway's policy-decision filter; builds and forwards the same parameters the Node gateway does to the same PDP.</li>
            <li><code>docs/authorization-decision-split.md</code> — full engineering audit of the split (file:line citations, decision-order trace, what's right and what's not).</li>
            <li><code>docs/gateway-enforcement-map.md</code> — this page's generated source doc.</li>
          </ul>
        </>
      ),
    },
  ];

  return (
    <EducationDrawer
      isOpen={isOpen}
      onClose={onClose}
      title="Gateway vs P1AZ — the decision split"
      subtitle="Where enforcement lives when the cloud PDP's DSL can't express a rule"
      tabs={tabs}
      initialTabId={initialTabId || 'overview'}
      width="min(720px, 100vw)"
    />
  );
}
