'use strict';

/**
 * Guard: every A2A specialist's declared `tools` must name a REAL, a2aDelegated tool.
 *
 * `config/a2aSpecialists.js` is the registry Agent 1 delegates through, and its `tools`
 * array is the sole input to three things that all fail QUIETLY when the name is wrong:
 *
 *   1. `deriveSpecialistScopes()` — the Exchange #1 scope, read from scope-topology's
 *      `a2aDelegatedScope`. A name with a scope-topology entry derives a scope happily
 *      even when no such tool can ever be executed.
 *   2. `delegateToSpecialist()`'s allowlist — a requested tool outside it is hard-rejected,
 *      and `allowedTools[0]` is what actually runs when no tool is requested.
 *   3. The `isA2aDelegatedTool()` fast-path — a tool NOT marked `a2aDelegated` never enters
 *      the delegation path at all; it degrades to an ordinary consent read.
 *
 * Investment shipped `sensitive_investment_holdings`, a name that existed ONLY as a
 * scope-topology `tools{}` key — no vertical plugin, no MCP tool schema, no gateway
 * backend. Scope derivation still "succeeded" (`holdings:read`), so nothing failed loudly:
 * the specialist path 502'd with no local-serve fallback (the plugin does not own that
 * name), while the `inv-a2a` chip dispatched plain `sensitive_holdings` — which is NOT
 * `a2aDelegated`, so it never built a nested-act chain. The demo looked like it worked.
 *
 * These assertions are the cheap, honest version of "the specialist can actually run
 * what it claims to run".
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../../');
const { A2A_SPECIALISTS } = require('../config/a2aSpecialists');
const { A2A_PRIMARY_TOOL_BY_VERTICAL } = require('../config/useCases');
const scopeTopology = require('../services/scopeTopology');
const { deriveSpecialistScopes } = require('../services/a2aDelegationService');

// The scopes an ordinary user bearer already carries. A "delegated" scope that is
// one of these has narrowed nothing.
const COARSE_SCOPES = new Set(['read', 'write']);
const topology = JSON.parse(fs.readFileSync(path.join(ROOT, 'scope-topology.json'), 'utf8'));

// mcp-tool-schemas.json is the generated union of every callable tool across the
// vertical plugins AND the gateway-served banking backend (235 today). It is
// regenerated by the .husky/pre-commit hook, so it cannot drift from the code.
const toolSchemas = JSON.parse(fs.readFileSync(path.join(ROOT, 'mcp-tool-schemas.json'), 'utf8'));
const REAL_TOOLS = new Set(Object.keys(toolSchemas.tools));

const declaredPairs = Object.entries(A2A_SPECIALISTS).flatMap(([vertical, specialist]) =>
  (specialist.tools || []).map((tool) => [vertical, tool]),
);

describe('a2aSpecialists registry — declared tools must be real and delegable', () => {
  test('every specialist declares at least one tool', () => {
    const empty = Object.entries(A2A_SPECIALISTS)
      .filter(([, s]) => !Array.isArray(s.tools) || s.tools.length === 0)
      .map(([v]) => v);
    expect(empty).toEqual([]);
  });

  test.each(declaredPairs)('%s: %s is a real, callable tool', (vertical, tool) => {
    // A name that exists only in scope-topology derives a scope but can never execute.
    expect(REAL_TOOLS.has(tool)).toBe(true);
  });

  test.each(declaredPairs)('%s: %s is marked a2aDelegated in scope-topology', (vertical, tool) => {
    // Without this the isA2aDelegatedTool() fast-path never fires and the chip silently
    // runs as an ordinary (non-A2A) tool call — the exact investment failure.
    expect(scopeTopology.isA2aDelegatedTool(tool)).toBe(true);
  });

  // Drives the REAL exported derivation, not a local replica of it. The replica this
  // replaces asserted only `length > 0`, which a collapse to bare ["read"] passes —
  // and retail/sporting-goods/workforce shipped exactly that, unnoticed, until the
  // rt-a2a/sg-a2a/wf-a2a chips put three such chains in front of users.
  test.each(Object.entries(A2A_SPECIALISTS))(
    '%s: Exchange #2 requests a DEDICATED scope, never a coarse one',
    (vertical, specialist) => {
      const scopes = deriveSpecialistScopes(specialist, scopeTopology);
      expect(scopes.length).toBeGreaterThan(0);
      // `read`/`write` are what every ordinary bearer already carries. Requesting one
      // of them proves no narrowing happened, so the delegated token is no more
      // constrained than the user's own — the least-privilege claim the A2A demo
      // makes is then false. REGRESSION_PLAN 2026-07-27 forbids it by name.
      const coarse = scopes.filter((s) => COARSE_SCOPES.has(s));
      expect(coarse).toEqual([]);
    },
  );

  test.each(Object.entries(A2A_SPECIALISTS))(
    '%s: its delegated scope is grantable — declared and on the A2A gateway resource',
    (vertical, specialist) => {
      // A scope the runtime requests but no resource offers fails Exchange #2 with
      // PingOne invalid_scope, i.e. the collapse-avoidance above must not be won by
      // inventing a scope name that was never provisioned.
      const a2aGw = new Set(topology.resources['Super Banking A2A MCP Gateway'].scopes);
      const problems = deriveSpecialistScopes(specialist, scopeTopology).flatMap((s) => [
        ...(topology.scopes[s] ? [] : [`${s} is not declared in scopes{}`]),
        ...(a2aGw.has(s) ? [] : [`${s} is missing from the Super Banking A2A MCP Gateway resource`]),
      ]);
      expect(problems).toEqual([]);
    },
  );

  test("UC2's per-vertical A2A primary tool is one the specialist is allowed to run", () => {
    // useCases.js documents this invariant in prose ("Each entry maps to a tool marked
    // a2aDelegated:true in scope-topology.json and registered in a2aSpecialists.js").
    // delegateToSpecialist() hard-rejects anything outside the allowlist, so a mismatch
    // here is a guaranteed runtime error on the UC2 chip.
    const mismatches = [];
    for (const [vertical, tool] of Object.entries(A2A_PRIMARY_TOOL_BY_VERTICAL)) {
      const specialist = A2A_SPECIALISTS[vertical];
      if (!specialist) {
        mismatches.push(`${vertical}: UC2 names ${tool} but no specialist is registered`);
        continue;
      }
      if (!(specialist.tools || []).includes(tool)) {
        mismatches.push(
          `${vertical}: UC2 dispatches ${tool} but ${specialist.specialistName} is only allowed ${(specialist.tools || []).join(', ')}`,
        );
      }
    }
    expect(mismatches).toEqual([]);
  });
});
