'use strict';

/**
 * Guard: every A2A specialist's declared `tools` must name a REAL, a2aDelegated tool.
 *
 * `config/a2aSpecialists.js` is the registry Agent 1 delegates through, and its `tools`
 * array is the sole input to three things that all fail QUIETLY when the name is wrong:
 *
 *   1. `deriveSpecialistScopes()` — the Exchange #1 scope, read from scope-topology's
 *      `a2aDelegatedScope`. A name with a scope-topology entry derives a scope happily
 *      even when no such tool can ever be executed.
 *   2. `delegateToSpecialist()`'s allowlist — a requested tool outside it is hard-rejected,
 *      and `allowedTools[0]` is what actually runs when no tool is requested.
 *   3. The `isA2aDelegatedTool()` fast-path — a tool NOT marked `a2aDelegated` never enters
 *      the delegation path at all; it degrades to an ordinary consent read.
 *
 * Investment shipped `sensitive_investment_holdings`, a name that existed ONLY as a
 * scope-topology `tools{}` key — no vertical plugin, no MCP tool schema, no gateway
 * backend. Scope derivation still "succeeded" (`holdings:read`), so nothing failed loudly:
 * the specialist path 502'd with no local-serve fallback (the plugin does not own that
 * name), while the `inv-a2a` chip dispatched plain `sensitive_holdings` — which is NOT
 * `a2aDelegated`, so it never built a nested-act chain. The demo looked like it worked.
 *
 * These assertions are the cheap, honest version of "the specialist can actually run
 * what it claims to run".
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../../');
const { A2A_SPECIALISTS } = require('../config/a2aSpecialists');
const { A2A_PRIMARY_TOOL_BY_VERTICAL } = require('../config/useCases');
const scopeTopology = require('../services/scopeTopology');
const { verticalManifest } = require('../services/verticalManifest');

verticalManifest.init();

// mcp-tool-schemas.json is the generated union of every callable tool across the
// vertical plugins AND the gateway-served banking backend (238 today). It is
// regenerated by the .husky/pre-commit hook, so it cannot drift from the code.
const toolSchemas = JSON.parse(fs.readFileSync(path.join(ROOT, 'mcp-tool-schemas.json'), 'utf8'));
const SCHEMA_TOOLS = new Set(Object.keys(toolSchemas.tools));

/**
 * "Real" means SOMETHING can answer the name — which is not the same as "is in the
 * generated schema union".
 *
 * scripts/gen-vertical-tools.js walks verticalManifest.list(), and that walk applies
 * HIDDEN_IDS (admin, admin-console, oauth-teaching — the verticals kept out of the
 * switcher). So the `admin` vertical's tools never reach the generated catalogs or
 * mcp-tool-schemas.json, however real they are; hand-adding them there fails
 * `verticals:check`, which compares the whole rendered file.
 *
 * Being owned by the vertical's own plugin is the stronger evidence anyway — it is
 * what the local-serve path in executeA2aDelegation actually requires, and it is
 * exactly what the investment ghost (`sensitive_investment_holdings`) lacked: no
 * plugin advertised it, so the specialist 502'd and the fallback declined.
 */
function pluginOwns(vertical, tool) {
  const plugin = verticalManifest.plugins.get(vertical);
  if (!plugin || typeof plugin.getTools !== 'function') return false;
  return plugin.getTools().some((t) => t && t.name === tool);
}

const declaredPairs = Object.entries(A2A_SPECIALISTS).flatMap(([vertical, specialist]) =>
  (specialist.tools || []).map((tool) => [vertical, tool]),
);

describe('a2aSpecialists registry — declared tools must be real and delegable', () => {
  test('every specialist declares at least one tool', () => {
    const empty = Object.entries(A2A_SPECIALISTS)
      .filter(([, s]) => !Array.isArray(s.tools) || s.tools.length === 0)
      .map(([v]) => v);
    expect(empty).toEqual([]);
  });

  test.each(declaredPairs)('%s: %s is a real, callable tool', (vertical, tool) => {
    // A name that exists only in scope-topology derives a scope but can never execute.
    expect(`${tool}:${SCHEMA_TOOLS.has(tool) || pluginOwns(vertical, tool)}`).toBe(`${tool}:true`);
  });

  test.each(declaredPairs)('%s: %s runs — it is not a name nothing answers to', async (vertical, tool) => {
    const plugin = verticalManifest.plugins.get(vertical);
    if (!plugin) {
      // Only banking has no plugin of its own; its tools are in the schema union.
      expect(`${vertical}:${SCHEMA_TOOLS.has(tool)}`).toBe(`${vertical}:true`);
      return;
    }
    const out = await plugin.executeTool(tool, {}, { userId: 'demoUser' });
    // An undeclared action returns `{ result: { error: 'unknown <x> action: …' } }`.
    // A tool handed to the MCP executor legitimately returns no local payload, and
    // that IS a dispatch — so only the unknown-action shape fails.
    expect(String(out?.result?.error || '')).not.toMatch(/unknown/i);
  });

  test('NEGATIVE PROOF: a fabricated name satisfies neither source', () => {
    expect(SCHEMA_TOOLS.has('sensitive_investment_holdings')).toBe(false);
    expect(pluginOwns('investment', 'sensitive_investment_holdings')).toBe(false);
  });

  test.each(declaredPairs)('%s: %s is marked a2aDelegated in scope-topology', (vertical, tool) => {
    // Without this the isA2aDelegatedTool() fast-path never fires and the chip silently
    // runs as an ordinary (non-A2A) tool call — the exact investment failure.
    expect(scopeTopology.isA2aDelegatedTool(tool)).toBe(true);
  });

  test.each(declaredPairs)('%s: %s derives a non-empty Exchange #1 scope', (vertical, tool) => {
    const delegated = scopeTopology.a2aDelegatedScope(tool);
    const scopes = delegated ? [delegated] : scopeTopology.toolScopes(tool) || [];
    expect(scopes.length).toBeGreaterThan(0);
  });

  test("UC2's per-vertical A2A primary tool is one the specialist is allowed to run", () => {
    // useCases.js documents this invariant in prose ("Each entry maps to a tool marked
    // a2aDelegated:true in scope-topology.json and registered in a2aSpecialists.js").
    // delegateToSpecialist() hard-rejects anything outside the allowlist, so a mismatch
    // here is a guaranteed runtime error on the UC2 chip.
    const mismatches = [];
    for (const [vertical, tool] of Object.entries(A2A_PRIMARY_TOOL_BY_VERTICAL)) {
      const specialist = A2A_SPECIALISTS[vertical];
      if (!specialist) {
        mismatches.push(`${vertical}: UC2 names ${tool} but no specialist is registered`);
        continue;
      }
      if (!(specialist.tools || []).includes(tool)) {
        mismatches.push(
          `${vertical}: UC2 dispatches ${tool} but ${specialist.specialistName} is only allowed ${(specialist.tools || []).join(', ')}`,
        );
      }
    }
    expect(mismatches).toEqual([]);
  });
});

