// GatewayEnforcementMapPage.jsx — standalone view of the generated gateway
// enforcement diagram (same source the Learning Hub "Gateway vs P1AZ Decision
// Split" panel renders). Source of truth: scripts/gen-gateway-enforcement-map.js
// — re-run it after touching any of the files it scans; this page updates
// automatically since it imports the generated output, never a hand-typed copy.
import React, { useState } from "react";
import DiagramExportBar from "./DiagramExportBar";
import { useMermaidRender } from "../hooks/useMermaidRender";
import {
  GATEWAY_ENFORCEMENT_JOURNEY_MERMAID,
  GATEWAY_ENFORCEMENT_STAKES,
  GATEWAY_ENFORCEMENT_ROWS,
} from "./education/gatewayEnforcementDiagram.generated";
import "./GatewayEnforcementMapPage.css";

const FLOWCHART_OPTS = { htmlLabels: true, useMaxWidth: true, curve: "basis" };

const STATUS_LABEL = {
  done: "✅ enforced",
  bydesign: "✅ P1AZ owns the decision",
  flagged: "✅ built · opt-in flag",
  pending: "planned — P1AZ covers it today",
};

// Colors for each tier live in GatewayEnforcementMapPage.css (.gwe-verdict--*).
const VERDICT_ICON = {
  done: "✅",
  bydesign: "✅",
  flagged: "✅",
  pending: "⚠️",
};

const THEME_VARS = { fontSize: "20px" };

export default function GatewayEnforcementMapPage() {
  const [source, setSource] = useState(GATEWAY_ENFORCEMENT_JOURNEY_MERMAID);
  const { containerRef, error: renderError } = useMermaidRender(source, {
    themeVariables: THEME_VARS,
    flowchart: FLOWCHART_OPTS,
  });

  return (
    <div className="gwe-page">
      <span className="gwe-eyebrow">demo_mcp_gateway + ping-gateway + PingOne Authorize</span>
      <h1>Enforcement Map — Gateway + P1AZ</h1>
      <p className="gwe-desc">
        All 5 checks below are enforced today, at the gateway that owns them — generated by
        grepping the real source, not hand-maintained. Re-run{" "}
        <code>node scripts/gen-gateway-enforcement-map.js</code> after a code change and this
        page updates with it.
      </p>
      <p className="gwe-reading-note">
        <strong>Reading the diagram:</strong> P1AZ (the cloud PDP) decides business policy —
        amount, tier, group, step-up, HITL. These 5 checks run at the PEP instead, where the
        raw token claims and call parameters live. Each branches to the gateway that enforces
        it, then reconverges on one decision. Box color shows which gateway carries it.
      </p>

      <DiagramExportBar
        source={source}
        sourceFilename="gateway-enforcement-map.mmd"
        onSourceChange={setSource}
      />

      {renderError ? (
        <p className="gwe-error">Diagram failed to render: {renderError}</p>
      ) : (
        <div ref={containerRef} role="img" aria-label="Gateway enforcement journey" style={{ overflow: "auto", margin: "12px 0" }} />
      )}

      <h2 className="gwe-section-title">What each check stops</h2>
      <div className="gwe-stakes">
        {GATEWAY_ENFORCEMENT_STAKES.map((s) => (
          <div key={s.id} className="gwe-stakes-card">
            <div className="gwe-stakes-card-label">{s.label}</div>
            <div className="gwe-stakes-card-scenario">{s.scenario}</div>
            <div className={`gwe-verdict gwe-verdict--${s.verdictTier}`}>
              <span>{VERDICT_ICON[s.verdictTier]}</span>
              <span>{s.verdictText}</span>
            </div>
          </div>
        ))}
      </div>

      <table className="edu-table gwe-table">
        <thead>
          <tr><th>Check</th><th>Why the gateway owns it</th><th>Node gateway</th><th>IG gateway (groovy)</th></tr>
        </thead>
        <tbody>
          {GATEWAY_ENFORCEMENT_ROWS.map((row) => (
            <tr key={row.id}>
              <td>{row.label}</td>
              <td className="gwe-table-p1az">{row.p1az}</td>
              <td>{STATUS_LABEL[row.node.status]}</td>
              <td>{STATUS_LABEL[row.groovy.status]}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="gwe-rar-note">
        <strong>Why RAR runs opt-in — two switches, two reasons</strong>
        <p>
          <code>ff_rar</code> is off by default because PingOne SaaS accepts{" "}
          <code>authorization_details</code> on <strong>PAR</strong> only — it never mints them
          into the access token. So with <code>ff_rar</code> ON the BFF builds the grant and
          carries it in the trusted TraT <code>azd</code> envelope; the grant is minted natively
          on PingOne AIC / PingFederate 11.2+.
        </p>
        <p>
          <code>PG_LOCAL_RAR_PAYEE_ENFORCE</code> is a separate switch on the IG path, and it is
          off on purpose: the groovy filter forwards the RAR attributes and lets P1AZ's{" "}
          <code>RarMaxAmount</code> rule decide, rather than denying locally. Both gateways cover
          the check — one locally, one by delegation.
        </p>
      </div>

      <p className="gwe-footer">
        See the Learning Hub &rarr; Standards &amp; Architecture &rarr; "Gateway vs P1AZ Decision
        Split" for the full write-up, or docs/gateway-enforcement-map.md for the repo copy.
      </p>
    </div>
  );
}
