// GatewayEnforcementMapPage.jsx — standalone view of the generated gateway
// enforcement diagram (same source the Learning Hub "Gateway vs P1AZ Decision
// Split" panel renders). Source of truth: scripts/gen-gateway-enforcement-map.js
// — re-run it after touching any of the files it scans; this page updates
// automatically since it imports the generated output, never a hand-typed copy.
import React, { useEffect, useRef, useState } from "react";
import mermaid from "mermaid";
import DiagramExportBar from "./DiagramExportBar";
import {
  GATEWAY_ENFORCEMENT_MERMAID,
  GATEWAY_ENFORCEMENT_ROWS,
} from "./education/gatewayEnforcementDiagram.generated";

const STATUS_LABEL = {
  done: "✅ enforced",
  flagged: "⚠️ built, default OFF",
  pending: "❌ gap",
};

export default function GatewayEnforcementMapPage() {
  const containerRef = useRef(null);
  const [source, setSource] = useState(GATEWAY_ENFORCEMENT_MERMAID);
  const [renderError, setRenderError] = useState(null);
  const renderIdRef = useRef(0);

  useEffect(() => {
    let cancelled = false;
    setRenderError(null);
    mermaid.initialize({
      startOnLoad: false,
      theme: "default",
      securityLevel: "loose",
      themeVariables: { fontSize: "20px" },
      flowchart: { htmlLabels: true, useMaxWidth: true, curve: "basis" },
    });
    (async () => {
      try {
        const id = `gateway-enforcement-map-svg-${++renderIdRef.current}`;
        const { svg } = await mermaid.render(id, source);
        if (!cancelled && containerRef.current) containerRef.current.innerHTML = svg;
      } catch (err) {
        if (!cancelled) setRenderError(err?.message || "Mermaid render failed");
      }
    })();
    return () => { cancelled = true; };
  }, [source]);

  return (
    <div style={{ padding: "24px", maxWidth: 1100, margin: "0 auto" }}>
      <span style={{ fontSize: 12, opacity: 0.65 }}>demo_mcp_gateway + ping-gateway + PingOne Authorize</span>
      <h1 style={{ marginTop: 4 }}>Gateway vs P1AZ — Enforcement Map</h1>
      <p style={{ opacity: 0.85, maxWidth: 760 }}>
        Where each of the 5 rules PingOne Authorize's decision DSL can't express is actually
        enforced today — generated by grepping the real source, not hand-maintained. Re-run{" "}
        <code>node scripts/gen-gateway-enforcement-map.js</code> after a code change and this
        page updates with it.
      </p>

      <DiagramExportBar
        source={source}
        sourceFilename="gateway-enforcement-map.mmd"
        onSourceChange={setSource}
      />

      {renderError ? (
        <p style={{ color: "#dc2626" }}>Diagram failed to render: {renderError}</p>
      ) : (
        <div ref={containerRef} role="img" aria-label="Gateway enforcement map" style={{ overflow: "auto", margin: "12px 0" }} />
      )}

      <table className="edu-table" style={{ marginTop: 8 }}>
        <thead>
          <tr><th>Rule</th><th>Node gateway</th><th>IG gateway (groovy)</th></tr>
        </thead>
        <tbody>
          {GATEWAY_ENFORCEMENT_ROWS.map((row) => (
            <tr key={row.id}>
              <td>{row.label}</td>
              <td>{STATUS_LABEL[row.node.status]}</td>
              <td>{STATUS_LABEL[row.groovy.status]}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p style={{ opacity: 0.6, fontSize: 12, marginTop: 16 }}>
        See the Learning Hub &rarr; Standards &amp; Architecture &rarr; "Gateway vs P1AZ Decision
        Split" for the full write-up, or docs/gateway-enforcement-map.md for the repo copy.
      </p>
    </div>
  );
}
