// GatewayEnforcementMapPage.jsx — standalone view of the generated gateway
// enforcement diagram (same source the Learning Hub "Gateway vs P1AZ Decision
// Split" panel renders). Source of truth: scripts/gen-gateway-enforcement-map.js
// — re-run it after touching any of the files it scans; this page updates
// automatically since it imports the generated output, never a hand-typed copy.
import React, { useEffect, useRef, useState } from "react";
import mermaid from "mermaid";
import DiagramExportBar from "./DiagramExportBar";
import {
  GATEWAY_ENFORCEMENT_JOURNEY_MERMAID,
  GATEWAY_ENFORCEMENT_STAKES,
  GATEWAY_ENFORCEMENT_ROWS,
} from "./education/gatewayEnforcementDiagram.generated";

const STATUS_LABEL = {
  done: "✅ enforced",
  bydesign: "✅ P1AZ owns the decision",
  flagged: "✅ built · opt-in flag",
  pending: "planned — P1AZ covers it today",
};

const VERDICT_STYLE = {
  done: { bg: "#0a2418", fg: "#6ee7b7", border: "#059669", icon: "✅" },
  bydesign: { bg: "#062b2b", fg: "#5eead4", border: "#0d9488", icon: "✅" },
  flagged: { bg: "#2a1a00", fg: "#fbbf24", border: "#d97706", icon: "✅" },
  pending: { bg: "#2d0a0a", fg: "#fca5a5", border: "#dc2626", icon: "⚠️" },
};

export default function GatewayEnforcementMapPage() {
  const containerRef = useRef(null);
  const [source, setSource] = useState(GATEWAY_ENFORCEMENT_JOURNEY_MERMAID);
  const [renderError, setRenderError] = useState(null);
  const renderIdRef = useRef(0);

  useEffect(() => {
    let cancelled = false;
    setRenderError(null);
    mermaid.initialize({
      startOnLoad: false,
      theme: "default",
      securityLevel: "loose",
      themeVariables: { fontSize: "20px" },
      flowchart: { htmlLabels: true, useMaxWidth: true, curve: "basis" },
    });
    (async () => {
      try {
        const id = `gateway-enforcement-map-svg-${++renderIdRef.current}`;
        const { svg } = await mermaid.render(id, source);
        if (!cancelled && containerRef.current) containerRef.current.innerHTML = svg;
      } catch (err) {
        if (!cancelled) setRenderError(err?.message || "Mermaid render failed");
      }
    })();
    return () => { cancelled = true; };
  }, [source]);

  return (
    <div style={{ padding: "24px", maxWidth: 1100, margin: "0 auto" }}>
      <span style={{ fontSize: 12, opacity: 0.65 }}>demo_mcp_gateway + ping-gateway + PingOne Authorize</span>
      <h1 style={{ marginTop: 4 }}>Enforcement Map — Gateway + P1AZ</h1>
      <p style={{ opacity: 0.85, maxWidth: 760 }}>
        All 5 checks below are enforced today, at the gateway that owns them — generated by
        grepping the real source, not hand-maintained. Re-run{" "}
        <code>node scripts/gen-gateway-enforcement-map.js</code> after a code change and this
        page updates with it.
      </p>
      <p style={{ opacity: 0.7, maxWidth: 760, fontSize: 13 }}>
        <strong>Reading the diagram:</strong> P1AZ (the cloud PDP) decides business policy —
        amount, tier, group, step-up, HITL. These 5 checks run at the PEP instead, where the
        raw token claims and call parameters live. Each branches to the gateway that enforces
        it, then reconverges on one decision. Box color shows which gateway carries it.
      </p>

      <DiagramExportBar
        source={source}
        sourceFilename="gateway-enforcement-map.mmd"
        onSourceChange={setSource}
      />

      {renderError ? (
        <p style={{ color: "#dc2626" }}>Diagram failed to render: {renderError}</p>
      ) : (
        <div ref={containerRef} role="img" aria-label="Gateway enforcement journey" style={{ overflow: "auto", margin: "12px 0" }} />
      )}

      <h2 style={{ fontSize: 16, marginTop: 32 }}>What each check stops</h2>
      <div style={{ display: "flex", gap: 14, overflowX: "auto", paddingBottom: 8 }}>
        {GATEWAY_ENFORCEMENT_STAKES.map((s) => {
          const style = VERDICT_STYLE[s.verdictTier];
          return (
            <div
              key={s.id}
              style={{
                background: "var(--th-bg-card)",
                border: "1px solid var(--th-border)",
                borderRadius: 10,
                padding: 18,
                minWidth: 260,
                maxWidth: 260,
                flexShrink: 0,
                display: "flex",
                flexDirection: "column",
                gap: 10,
              }}
            >
              <div style={{ fontSize: 14, fontWeight: 600, color: "var(--th-text)" }}>{s.label}</div>
              <div style={{ fontSize: 12.5, color: "var(--th-text-muted)", lineHeight: 1.5, fontStyle: "italic" }}>
                {s.scenario}
              </div>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 8,
                  fontSize: 12,
                  padding: "8px 10px",
                  borderRadius: 6,
                  background: style.bg,
                  color: style.fg,
                  border: `1px solid ${style.border}`,
                }}
              >
                <span>{style.icon}</span>
                <span>{s.verdictText}</span>
              </div>
            </div>
          );
        })}
      </div>

      <table className="edu-table" style={{ marginTop: 8 }}>
        <thead>
          <tr><th>Check</th><th>Why the gateway owns it</th><th>Node gateway</th><th>IG gateway (groovy)</th></tr>
        </thead>
        <tbody>
          {GATEWAY_ENFORCEMENT_ROWS.map((row) => (
            <tr key={row.id}>
              <td>{row.label}</td>
              <td style={{ fontSize: 12.5, opacity: 0.85, maxWidth: 360 }}>{row.p1az}</td>
              <td>{STATUS_LABEL[row.node.status]}</td>
              <td>{STATUS_LABEL[row.groovy.status]}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div
        style={{
          marginTop: 16,
          padding: "14px 16px",
          borderRadius: 8,
          background: "var(--th-bg-card)",
          border: "1px solid var(--th-border)",
          fontSize: 12.5,
          lineHeight: 1.6,
          color: "var(--th-text-muted)",
          maxWidth: 900,
        }}
      >
        <strong style={{ color: "var(--th-text)" }}>Why RAR runs opt-in — two switches, two reasons</strong>
        <p style={{ margin: "6px 0 0" }}>
          <code>ff_rar</code> is off by default because PingOne SaaS accepts{" "}
          <code>authorization_details</code> on <strong>PAR</strong> only — it never mints them
          into the access token. So with <code>ff_rar</code> ON the BFF builds the grant and
          carries it in the trusted TraT <code>azd</code> envelope; the grant is minted natively
          on PingOne AIC / PingFederate 11.2+.
        </p>
        <p style={{ margin: "6px 0 0" }}>
          <code>PG_LOCAL_RAR_PAYEE_ENFORCE</code> is a separate switch on the IG path, and it is
          off on purpose: the groovy filter forwards the RAR attributes and lets P1AZ's{" "}
          <code>RarMaxAmount</code> rule decide, rather than denying locally. Both gateways cover
          the check — one locally, one by delegation.
        </p>
      </div>

      <p style={{ opacity: 0.6, fontSize: 12, marginTop: 16 }}>
        See the Learning Hub &rarr; Standards &amp; Architecture &rarr; "Gateway vs P1AZ Decision
        Split" for the full write-up, or docs/gateway-enforcement-map.md for the repo copy.
      </p>
    </div>
  );
}
