#!/bin/bash
# k8s/create-secrets.sh — create K8s secrets from local files
# Run once before deploy.sh, or re-run to rotate.
#
# Mirrors docker-compose's per-service env_file model: each service that has its
# own .env in the repo gets its own K8s secret, so MCP / langchain / agents
# receive the same credentials they do under `docker compose`.
#
# Quote handling: we SOURCE each .env (shell strips quotes) and emit
# --from-literal pairs. We deliberately do NOT use --from-env-file, which keeps
# surrounding quotes literally and corrupts secrets containing ~ . - etc.
#
# Prerequisites:
#   - demo_api_server/.env must exist (generated by bootstrap)
#   - certs/api.ping.demo+2.pem and certs/api.ping.demo+2-key.pem must exist
#   - (optional) <HELIX_AGENT_ID>.json keyfile (e.g. LLM2.json) for HELIX_API_KEY,
#     unless HELIX_API_KEY is already set in demo_api_server/.env
#
# Worktree fallback: .env files and certs are gitignored machine-local assets,
# so they do NOT travel to linked git worktrees. When this script runs from a
# worktree that lacks them, we transparently source the assets from the primary
# checkout (resolved via `git rev-parse --git-common-dir`) instead of failing.

set -e

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --check|--dry-run) DRY_RUN=1 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NS="${K8S_NAMESPACE:-ai-demo}"

# Snapshot the caller's PUBLIC_APP_URL before any secret_from_envfile call can
# clobber it: secret_from_envfile does `set -o allexport; source $env_file`,
# which pollutes THIS script's own variable namespace with every key in each
# service .env — including PUBLIC_APP_URL from demo_api_server/.env (the
# local dev default). That silently overwrites a caller-supplied
# PUBLIC_APP_URL before override_redirect_uris_for_public_origin ever reads
# it, even when the caller exported it correctly. Broke live sign-in twice
# (2026-07-13) via the normal se-update-code.sh path, not just standalone runs.
CALLER_PUBLIC_APP_URL="${PUBLIC_APP_URL:-}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

info()    { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
die()     { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Resolve where the gitignored, machine-local assets actually live ─────────
# Prefer this checkout. If its .env is missing (typical when running from a git
# worktree, since gitignored files don't get checked out there), fall back to
# the primary checkout that owns the shared .git directory.
ASSET_ROOT="$REPO_ROOT"
if [ ! -f "$ASSET_ROOT/demo_api_server/.env" ]; then
  if git_common="$(git -C "$REPO_ROOT" rev-parse --git-common-dir 2>/dev/null)"; then
    case "$git_common" in
      /*) : ;;                                   # already absolute
      *)  git_common="$REPO_ROOT/$git_common" ;; # relativize to this checkout
    esac
    primary_root="$(cd "$(dirname "$git_common")" && pwd)"
    if [ "$primary_root" != "$REPO_ROOT" ] && [ -f "$primary_root/demo_api_server/.env" ]; then
      warn "demo_api_server/.env not found under $REPO_ROOT (likely a git worktree)."
      warn "Falling back to primary checkout for machine-local assets: $primary_root"
      ASSET_ROOT="$primary_root"
    fi
  fi
fi

# ── --check/--dry-run scope warning ───────────────────────────────────────────
# The flag only wraps secret_from_envfile()'s own value-resolution report (per
# the plan's Testing section — a vault-vs-.env SOURCE preview, not a whole-
# script dry-run). Every other mutation below (TLS-certs apply, service-API-key
# / internal-secret alignment, Helix/Google/Groq/Anthropic key mirroring,
# ping-mcpgw-secrets, ping-gateway-config, and the final rollout-restart loop)
# still runs for real. Say so loudly so nobody mistakes --check for a safe
# no-op against a live shared cluster.
if [ "$DRY_RUN" = "1" ]; then
  warn "--check/--dry-run only previews vault-vs-.env value SOURCE for secret_from_envfile() calls."
  warn "It is NOT a full dry-run — this run still performs every other kubectl mutation in this script"
  warn "(TLS-certs apply, key alignment/mirroring, ping-mcpgw-secrets, ping-gateway-config, and the"
  warn "final rollout-restart of every deployment in namespace $NS)."
fi

# ── Vault: preflight + cache the key list once, before ANY kubectl call, so a
# missing/wrong VAULT_PASSWORD aborts before this script touches the live
# cluster at all (a vault failure discovered only at the first
# secret_from_envfile() call would leave the tls-certs secret already applied
# — a partial write). Fail closed: no vault script, no VAULT_PASSWORD → abort,
# don't silently fall back to .env for what should be vault-only secrets.
VAULT_SCRIPT="$REPO_ROOT/demo_api_server/scripts/vault.js"
[ -f "$VAULT_SCRIPT" ] || die "vault script not found at $VAULT_SCRIPT"
# secrets.vault is gitignored, same worktree-fallback need as VAULT_PASSWORD
# below — default to ASSET_ROOT (main checkout when run from a worktree)
# rather than requiring every caller to export VAULT_PATH by hand.
export VAULT_PATH="${VAULT_PATH:-$ASSET_ROOT/secrets.vault}"
if [ -z "${VAULT_PASSWORD:-}" ] && [ -f "$ASSET_ROOT/demo_api_server/.env" ]; then
  VAULT_PASSWORD="$(grep -E '^VAULT_PASSWORD=.+' "$ASSET_ROOT/demo_api_server/.env" | head -1 | cut -d= -f2- | tr -d '"')"
fi
[ -n "${VAULT_PASSWORD:-}" ] || die "VAULT_PASSWORD is required (export it, or set it in demo_api_server/.env)"
info "Reading vault key list..."
VAULT_KEYS="$(VAULT_PASSWORD="$VAULT_PASSWORD" node "$VAULT_SCRIPT" list)" \
  || die "vault: failed to list keys — check VAULT_PASSWORD and secrets.vault"

vault_has_key() {
  # Exact-line match against the cached newline-separated key list.
  printf '%s\n' "$VAULT_KEYS" | grep -qxF -- "$1"
}

vault_get() {
  VAULT_PASSWORD="$VAULT_PASSWORD" node "$VAULT_SCRIPT" get "$1" \
    || die "vault: failed to read $1"
}

# ── Preflight ─────────────────────────────────────────────────────────────────
[ -f "$ASSET_ROOT/demo_api_server/.env" ] || die "demo_api_server/.env not found. Run bootstrap first."
[ -f "$ASSET_ROOT/certs/api.ping.demo+2.pem" ]     || die "certs/api.ping.demo+2.pem not found. Run bootstrap first."
[ -f "$ASSET_ROOT/certs/api.ping.demo+2-key.pem" ] || die "certs/api.ping.demo+2-key.pem not found. Run bootstrap first."
[ -f "$ASSET_ROOT/certs/rootCA.pem" ]              || die "certs/rootCA.pem not found. Run ./run.sh once to copy the mkcert root CA."
kubectl get ns "$NS" &>/dev/null || die "Namespace $NS not found. Apply 01-namespace.yaml first."

# ── TLS secret from mkcert certs ─────────────────────────────────────────────
info "Creating tls-certs secret..."
# ca-bundle-with-mkcert.pem (system roots + mkcert root CA) lets the Python
# agents verify the BFF's mkcert cert via SSL_CERT_FILE without breaking
# external HTTPS — same bundle docker-compose mounts. Ship it when present.
CA_BUNDLE_ARG=()
if [ -f "$ASSET_ROOT/certs/ca-bundle-with-mkcert.pem" ]; then
  CA_BUNDLE_ARG=(--from-file=ca-bundle-with-mkcert.pem="$ASSET_ROOT/certs/ca-bundle-with-mkcert.pem")
fi
# pg-server.p12: PingGateway's admin.json (HTTPS 3036 change, 2026-08-17) fatals
# at startup with "The file related to the keystore does not exist" without it.
# Generated locally by scripts/ensure-pinggateway-tls-cert.sh (gitignored).
PG_TLS_ARG=()
if [ -f "$ASSET_ROOT/certs/pg-tls/pg-server.p12" ]; then
  PG_TLS_ARG=(--from-file=pg-server.p12="$ASSET_ROOT/certs/pg-tls/pg-server.p12")
else
  warn "  certs/pg-tls/pg-server.p12 missing — ping-gateway will crash-loop on its admin.json keystore; run scripts/ensure-pinggateway-tls-cert.sh and re-run this script"
fi
# Server-side apply: the CA bundle pushes the secret past the 256KB
# last-applied-configuration annotation limit of client-side apply.
kubectl create secret generic tls-certs \
  --namespace="$NS" \
  --from-file=tls.crt="$ASSET_ROOT/certs/api.ping.demo+2.pem" \
  --from-file=tls.key="$ASSET_ROOT/certs/api.ping.demo+2-key.pem" \
  --from-file=rootCA.pem="$ASSET_ROOT/certs/rootCA.pem" \
  "${CA_BUNDLE_ARG[@]}" \
  "${PG_TLS_ARG[@]}" \
  --dry-run=client -o yaml | kubectl apply --server-side --force-conflicts -f -
info "tls-certs secret applied."

# ── Helper: create one secret from a service's .env file ─────────────────────
# Usage: secret_from_envfile <secret-name> <path-to-.env>
secret_from_envfile() {
  local secret_name="$1" env_file="$2"
  # Optional 3rd arg: pass "legacy-env-only" for a service that deliberately
  # runs its own independent secret architecture outside the shared vault
  # (e.g. oauth-mcp, see oauth-mcp/src/vault.ts's own header comment — it was
  # migrated OFF secrets.vault on purpose). Skips vault consultation and the
  # drift guard-rail entirely for this one call, restoring pre-2026-08-25
  # .env-only behavior. Do not add this for any other service without the
  # same kind of documented, deliberate reason.
  local mode="${3:-}"
  if [ ! -f "$env_file" ]; then
    warn "  $env_file not found — skipping secret $secret_name"
    return
  fi

  local source_file="$env_file" decrypted_file=""
  if grep -qE '^[A-Za-z_][A-Za-z0-9_]*=encrypted:' "$env_file"; then
    local key_file="$ASSET_ROOT/.env.keys"
    local dotenvx_bin="$ASSET_ROOT/demo_api_server/node_modules/.bin/dotenvx"
    [ -f "$key_file" ] || die "Encrypted $env_file requires $key_file"
    [ -x "$dotenvx_bin" ] || die "Encrypted $env_file requires $dotenvx_bin (run npm install in demo_api_server)"
    local private_key
    private_key="$(source "$key_file" && printf '%s' "$DOTENV_PRIVATE_KEY")"
    [ -n "$private_key" ] || die "DOTENV_PRIVATE_KEY is missing from $key_file"
    decrypted_file="$(mktemp)"
    cp "$env_file" "$decrypted_file"
    DOTENV_PRIVATE_KEY="$private_key" "$dotenvx_bin" decrypt -f "$decrypted_file" >/dev/null \
      || { rm -f "$decrypted_file"; die "Could not decrypt $env_file"; }
    source_file="$decrypted_file"
  fi

  # Collect declared variable names (ignore comments/blank lines)
  local keys=()
  while IFS= read -r k; do
    [ -n "$k" ] && keys+=("$k")
  done < <(grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$source_file" | sed 's/=$//' | sort -u)

  # Source the file so quote-wrapped values are unquoted by the shell, then read
  # each declared key's value back. Sourcing here (right before reading) keeps
  # values correct even when two .env files share a key name.
  set -o allexport
  # shellcheck disable=SC1090
  source "$source_file"
  set +o allexport
  [ -z "$decrypted_file" ] || rm -f "$decrypted_file"

  local args=() dry_run_report=()
  for k in "${keys[@]}"; do
    local env_v="${!k:-}"
    if [ "$mode" != "legacy-env-only" ] && vault_has_key "$k"; then
      local vault_v
      vault_v="$(vault_get "$k")"
      if [ -n "$env_v" ] && [ "$env_v" != "$vault_v" ]; then
        die "SECURITY: $k is vault-managed and $env_file has a DIFFERENT non-empty value for it. The vault is authoritative — update $k in $env_file to match the vault value (or leave it blank), never leave a stale copy. (This is exactly the drift class that broke SE introspection on 2026-08-25 — see docs/superpowers/specs/2026-08-25-vault-in-k8s-design.md.)"
      fi
      [ -n "$vault_v" ] && args+=(--from-literal="${k}=${vault_v}")
      dry_run_report+=("$k -> vault")
    else
      [ -n "$env_v" ] && args+=(--from-literal="${k}=${env_v}")
      local mode_suffix=""
      [ "$mode" = "legacy-env-only" ] && mode_suffix=" (legacy-env-only)"
      dry_run_report+=("$k -> .env${mode_suffix}")
    fi
  done
  if [ "${DRY_RUN:-0}" = "1" ]; then
    printf '[dry-run] %s:\n' "$secret_name"
    printf '  %s\n' "${dry_run_report[@]}"
    return
  fi

  if [ "${#args[@]}" -eq 0 ]; then
    warn "  $env_file has no usable keys — skipping $secret_name"
    return
  fi

  kubectl create secret generic "$secret_name" \
    --namespace="$NS" \
    "${args[@]}" \
    --dry-run=client -o yaml | kubectl apply -f -
  info "  $secret_name applied (${#args[@]} keys from $(basename "$(dirname "$env_file")")/.env)"
}

# ── Helix agent key: source from the gitignored <agent>.json keyfile ──────────
# HELIX_API_KEY is a secret, so it is NOT committed (it is absent from the
# configmap and usually from .env). Mirror what the BFF does locally
# (helixAgentKeyLoader.js): read it from <HELIX_AGENT_ID>.json in the repo root
# (ASSET_ROOT) / ~/Documents / ~/Downloads, and patch it into ai-demo-secrets.
# Skipped (leaving the .env value in place) when HELIX_API_KEY is already set in
# the BFF .env, and a no-op when no keyfile is present.
inject_helix_api_key() {
  local bff_env="$ASSET_ROOT/demo_api_server/.env"
  if grep -qE '^HELIX_API_KEY=.+' "$bff_env" 2>/dev/null; then
    info "  HELIX_API_KEY already set in .env — keyfile lookup skipped"
    # Still mirror into langchain-secrets when the BFF .env has the key but
    # langchain_agent/.env does not (typical on SE/AWS deploys).
    local helix_key
    helix_key=$(grep -E '^HELIX_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
    if [ -n "$helix_key" ]; then
      export HELIX_KEY="$helix_key"
      python3 - <<'PY' | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
import json, os
print(json.dumps({"stringData": {"HELIX_API_KEY": os.environ["HELIX_KEY"], "LANGCHAIN_LLM_PROVIDER": "helix"}}))
PY
      info "  HELIX_API_KEY mirrored into langchain-secrets from BFF .env"
    fi
    return
  fi

  # Agent id: .env override wins, else the committed configmap/configStore default.
  local agent="LLM2"
  local env_agent
  env_agent=$(grep -E '^HELIX_AGENT_ID=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  [ -n "$env_agent" ] && agent="$env_agent"

  local keyfile=""
  local f
  for f in "$ASSET_ROOT/${agent}.json" "$HOME/Documents/${agent}.json" "$HOME/Downloads/${agent}.json"; do
    [ -f "$f" ] && { keyfile="$f"; break; }
  done
  if [ -z "$keyfile" ]; then
    warn "  No HELIX_API_KEY in .env and no ${agent}.json keyfile found — Helix will be unconfigured in-cluster"
    return
  fi

  # Emit the patch JSON from python (keyValue read from the file, never passed on
  # the command line); empty output if the file has no keyValue.
  local patch
  patch=$(python3 - "$keyfile" <<'PY'
import json, sys
try:
    k = (json.load(open(sys.argv[1])).get('keyValue') or '').strip()
except Exception:
    k = ''
if k:
    print(json.dumps({'stringData': {'HELIX_API_KEY': k}}))
PY
)
  if [ -z "$patch" ]; then
    warn "  $(basename "$keyfile") has no keyValue — HELIX_API_KEY not set"
    return
  fi
  printf '%s' "$patch" | kubectl patch secret ai-demo-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  info "  HELIX_API_KEY injected into ai-demo-secrets from $(basename "$keyfile")"
  # LangChain agent mounts langchain-secrets (not ai-demo-secrets) — mirror the key
  # and default provider so in-cluster /run and WebSocket chat use Helix on SE/AWS.
  printf '%s' "$patch" | python3 -c "
import json, sys
p = json.load(sys.stdin)
p['stringData']['LANGCHAIN_LLM_PROVIDER'] = 'helix'
print(json.dumps(p))
" | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  info "  HELIX_API_KEY + LANGCHAIN_LLM_PROVIDER=helix mirrored into langchain-secrets"
}

# Mirror GOOGLE_API_KEY from the BFF .env into langchain-secrets so the agent
# can honor an explicit Google/Gemini provider selection in the LLM config UI.
mirror_google_api_key() {
  local bff_env="$ASSET_ROOT/demo_api_server/.env"
  local google_key
  google_key=$(grep -E '^GOOGLE_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  if [ -z "$google_key" ]; then
    google_key=$(grep -E '^GEMINI_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  fi
  if [ -z "$google_key" ]; then
    return
  fi
  export GOOGLE_KEY="$google_key"
  python3 - <<'PY' | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
import json, os
print(json.dumps({"stringData": {"GOOGLE_API_KEY": os.environ["GOOGLE_KEY"]}}))
PY
  info "  GOOGLE_API_KEY mirrored into langchain-secrets from BFF .env"
}

# Mirror GROQ_API_KEY from the BFF .env into langchain-secrets so the agent
# can honor an explicit Groq provider selection (GroqCloud, OpenAI-compatible).
mirror_groq_api_key() {
  local bff_env="$ASSET_ROOT/demo_api_server/.env"
  local groq_key
  groq_key=$(grep -E '^GROQ_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  if [ -z "$groq_key" ]; then
    return
  fi
  export GROQ_KEY="$groq_key"
  python3 - <<'PY' | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
import json, os
print(json.dumps({"stringData": {"GROQ_API_KEY": os.environ["GROQ_KEY"]}}))
PY
  info "  GROQ_API_KEY mirrored into langchain-secrets from BFF .env"
}

# Mirror ANTHROPIC_API_KEY from the BFF .env into langchain-secrets so the agent
# can honor an explicit Anthropic/Claude provider selection.
#
# ANTHROPIC_API_KEY is declared in 03-secrets.yaml.template, but that populates
# ai-demo-secrets — which the LangChain agent does NOT mount (it mounts
# langchain-secrets, same trap as HELIX/GOOGLE/GROQ above). Without this mirror
# the key never reaches the pod, and an anthropic provider selection fails every
# run with `401 invalid x-api-key` (2026-07-14: this blocked every live-agent
# use case on the SE/AWS deploy).
mirror_anthropic_api_key() {
  local bff_env="$ASSET_ROOT/demo_api_server/.env"
  local anthropic_key
  anthropic_key=$(grep -E '^ANTHROPIC_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  if [ -z "$anthropic_key" ]; then
    return
  fi
  export ANTHROPIC_KEY="$anthropic_key"
  python3 - <<'PY' | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
import json, os
print(json.dumps({"stringData": {"ANTHROPIC_API_KEY": os.environ["ANTHROPIC_KEY"]}}))
PY
  info "  ANTHROPIC_API_KEY mirrored into langchain-secrets from BFF .env"
}

# ── Cloud override: redirect URIs must match the public origin ───────────────
# The BFF .env carries the LOCAL redirect URIs (https://api.ping.demo:4000/...).
# Shipping them verbatim breaks sign-in on any public deployment: these keys are
# bootstrap-authoritative (env beats the runtime config store), so the BFF sends
# PingOne a redirect_uri that only resolves on the dev machine. When
# PUBLIC_APP_URL is set (required for SE/EKS deploys), derive them from it.
#
# If this script is run standalone (e.g. to patch a single secret) without
# PUBLIC_APP_URL exported, fall back to whatever origin is already live in the
# target namespace's configmap instead of silently reverting to local values —
# this happened on live (2026-07-13) and broke sign-in for every user.
override_redirect_uris_for_public_origin() {
  local origin="${CALLER_PUBLIC_APP_URL:-}"
  if [ -z "$origin" ]; then
    origin=$(kubectl get configmap ai-demo-config --namespace="$NS" -o jsonpath='{.data.PUBLIC_APP_URL}' 2>/dev/null || true)
    if [ -n "$origin" ]; then
      warn "  PUBLIC_APP_URL not set — falling back to existing configmap origin $origin"
    fi
  fi
  if [ -z "$origin" ]; then
    warn "  PUBLIC_APP_URL not set and no existing configmap origin found — PINGONE_*_REDIRECT_URI/PUBLIC_APP_URL shipped as-is from .env (local values; sign-in will break on a public deployment)"
    return
  fi
  origin="${origin%/}"
  local patch
  patch=$(printf '{"stringData":{"PUBLIC_APP_URL":"%s","PINGONE_PUBLIC_APP_URL":"%s","PINGONE_ADMIN_REDIRECT_URI":"%s/api/auth/oauth/callback","PINGONE_USER_REDIRECT_URI":"%s/api/auth/oauth/user/callback"}}' "$origin" "$origin" "$origin" "$origin")
  printf '%s' "$patch" | kubectl patch secret ai-demo-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  info "  PUBLIC_APP_URL/PINGONE_PUBLIC_APP_URL/PINGONE_ADMIN/USER_REDIRECT_URI overridden to match $origin"
}

# ── Privilege gateway URLs: two places, two different fixes ─────────────────
# PRIVILEGE_AGENTLESS_MCPGW_URL (the BFF's Agentless target) and pingone.env's SERVER_URL (the
# gateway's own front door) both shipped from demo_api_server/.env and
# ping-mcpgw/procyon/config/pingone.env as-is — local values that don't
# resolve from inside the cluster.
#
# PRIVILEGE_MCPGW_URL used to be overridden to <origin>/mcpgw/mcp (the app's
# own se-ingress.yaml path). Proven live 2026-08-13 that this categorically
# cannot work for cyonproxy — that port is TLS-native (HTTP/2 via ALPN, its
# own certificate), and nginx re-encrypting it hits TLS handshake failures no
# matter the backend-protocol annotation (HTTP/HTTPS/GRPCS all tried against
# the real gateway). The Agentless Helm release instead exposes Streamable HTTP:
#   https://<namespace-owner>-agentless-mcpgw.ping-devops.com/<app-name>/mcp
# Keep this separate from PRIVILEGE_AGENT_MCPGW_URL: the Priv Agent frontend
# owns its authentication and must not inherit Agentless OAuth configuration.
override_privilege_urls_for_public_origin() {
  local origin="${CALLER_PUBLIC_APP_URL:-}"
  if [ -z "$origin" ]; then
    origin=$(kubectl get configmap ai-demo-config --namespace="$NS" -o jsonpath='{.data.PUBLIC_APP_URL}' 2>/dev/null || true)
  fi
  if [ -z "$origin" ]; then
    warn "  PUBLIC_APP_URL not set and no existing configmap origin found — PRIVILEGE_MCPGW_URL/SERVER_URL shipped as-is (local values; Privilege sign-in and tool calls will fail with fetch/DNS errors in-cluster)"
    return
  fi
  origin="${origin%/}"
  local mcpgw_base="${origin}/mcpgw"
  local app_name="${NS#ping-devops-}"
  local mcpgw_application="${MCPGW_APP_NAME:-$app_name}"
  local mcpgw_client_url="${PRIVILEGE_AGENTLESS_MCPGW_URL:-https://${app_name}-agentless-mcpgw.ping-devops.com/${mcpgw_application}/mcp}"

  # mcpgw binary routes by path prefix: /<app-name>/mcp (not just /mcp).
  # Set MCPGW_APP_NAME env var to the name registered in the Privilege console
  # (AI Security > Agentic Apps). Omit to get the flat /mcp path (won't work
  # with the mcpgw binary unless an app named "" exists, which it won't).
  local mcpgw_app_name="${MCPGW_APP_NAME:-}"
  local mcpgw_mcp_path
  if [ -n "$mcpgw_app_name" ]; then
    mcpgw_mcp_path="${mcpgw_base}/${mcpgw_app_name}/mcp"
  else
    mcpgw_mcp_path="${mcpgw_base}/mcp"
  fi

  local ai_patch
  ai_patch=$(printf '{"stringData":{"PRIVILEGE_AGENTLESS_MCPGW_URL":"%s","PRIVILEGE_MCPGW_URL":"%s"}}' "$mcpgw_client_url" "$mcpgw_client_url")
  printf '%s' "$ai_patch" | kubectl patch secret ai-demo-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  info "  PRIVILEGE_AGENTLESS_MCPGW_URL/PRIVILEGE_MCPGW_URL overridden to match ${mcpgw_client_url}"

  if [ -f "$ASSET_ROOT/ping-mcpgw/procyon/config/pingone.env" ]; then
    local patched_pingone_env
    patched_pingone_env=$(sed -E "s#^SERVER_URL=.*#SERVER_URL=${mcpgw_base}#" "$ASSET_ROOT/ping-mcpgw/procyon/config/pingone.env")
    local mcpgw_patch
    mcpgw_patch=$(printf '{"stringData":{"pingone.env":%s}}' "$(printf '%s' "$patched_pingone_env" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')")
    printf '%s' "$mcpgw_patch" | kubectl patch secret ping-mcpgw-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
    info "  ping-mcpgw-secrets pingone.env SERVER_URL overridden to match $mcpgw_base"
  fi
}

# ── Demo service API key (apikey-dispatch path) ──────────────────────────────
# The gateway pulls DEMO_API_RESOURCE_SERVER_KEY / DEMO_MCP_RESOURCE_SERVER_KEY from the
# BFF vault bridge and presents it to api-resource-server as X-API-Key. In-cluster
# the BFF has no vault password and no LMDB entry, so the bridge falls back to
# the committed default — while api-resource-server refuses to boot with that same
# default. Nothing else provisions the pair in k8s (ensure-service-keys.js is
# local-only), so a fresh deploy either crash-loops the backend or 401s every
# invest/mortgage chip ("backend rejected the service API key"). Single-source
# the key here: prefer the ensure-service-keys value from the repo-root .env,
# else mint one, then ship the SAME value to both sides (ai-demo-secrets for
# the BFF bridge, mortgage-secrets for the backend).
align_service_api_keys() {
  local key
  key=$(grep -E '^API_RESOURCE_SERVER_API_KEY=.+' "$ASSET_ROOT/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  case "$key" in
    ""|demo-mortgage-key-0000|mortgage-compose-dev-key)
      key="mortgage-$(openssl rand -hex 12)"
      warn "  API_RESOURCE_SERVER_API_KEY missing/default in repo-root .env — minted a deploy-local service key"
      ;;
  esac
  printf '{"stringData":{"DEMO_API_RESOURCE_SERVER_KEY":"%s","DEMO_MCP_RESOURCE_SERVER_KEY":"%s"}}' "$key" "$key" \
    | kubectl patch secret ai-demo-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  kubectl create secret generic mortgage-secrets \
    --namespace="$NS" \
    --from-literal="API_RESOURCE_SERVER_API_KEY=${key}" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  info "  Service API key aligned across ai-demo-secrets (bridge) + mortgage-secrets (backend)"
}

# BFF_INTERNAL_SECRET guards the internal-only endpoints (/internal/vault/service-key,
# /internal/id-token). 03-secrets.yaml.template ships it empty and nothing minted
# one, so both the BFF and the gateway fell back to the committed literal
# 'dev-shared-secret-change-me' — public knowledge in this repo. Any workload with
# pod-network reach to api-server:3001 could then read the backend service keys.
# Mint once and ship the SAME value to every consumer that compares it.
align_internal_secret() {
  local secret
  secret=$(grep -E '^BFF_INTERNAL_SECRET=.+' "$ASSET_ROOT/demo_api_server/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  case "$secret" in
    ""|dev-shared-secret-change-me)
      secret="$(openssl rand -hex 32)"
      warn "  BFF_INTERNAL_SECRET missing/default in demo_api_server/.env — minted a deploy-local internal secret"
      ;;
  esac
  # mcp-resource-server has no per-service .env / secret of its own (unlike the
  # other four) — create-or-update it here so the patch loop below has a target.
  # Scoped to just this one key, unlike reusing gateway-secrets/ai-demo-secrets,
  # which would leak unrelated worker/agent credentials into the resource server.
  kubectl create secret generic mcp-resource-server-secrets --namespace="$NS" \
    --from-literal=BFF_INTERNAL_SECRET="$secret" --dry-run=client -o yaml \
    | kubectl apply -f - >/dev/null 2>&1 || true
  local s
  # langchain-secrets belongs here too: langchain_agent compares this value in
  # its _gate_internal middleware (src/main.py), but it was omitted, so the
  # agent kept whatever langchain_agent/.env happened to carry. When the two
  # .env files disagreed the mismatch surfaced only as an opaque
  # `{"detail":"Invalid gateway secret"}` 403 on /api/codegraph/query — the
  # Code Explorer smoke check — with nothing naming the secret as the cause.
  # "agent-secrets" in this list is demo_agent_service, a different service.
  for s in ai-demo-secrets gateway-secrets agent-secrets langchain-secrets ping-gateway-secrets mcp-resource-server-secrets; do
    printf '{"stringData":{"BFF_INTERNAL_SECRET":"%s"}}' "$secret" \
      | kubectl patch secret "$s" --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null 2>&1 || true
  done
  info "  BFF_INTERNAL_SECRET aligned across BFF + gateway + agent + langchain + ping-gateway + mcp-resource-server"
}

# ── Per-service secrets (one per .env, mirroring docker-compose env_file) ─────
info "Creating per-service secrets from each service's .env..."
secret_from_envfile ai-demo-secrets   "$ASSET_ROOT/demo_api_server/.env"    # BFF (master)
override_redirect_uris_for_public_origin                                    # public origin beats local .env redirect URIs
align_service_api_keys                                                      # one key for the vault bridge AND the mortgage backend
secret_from_envfile mcp-secrets       "$ASSET_ROOT/oauth-mcp/.env" legacy-env-only  # MCP server — own independent secret architecture, see oauth-mcp/src/vault.ts
secret_from_envfile hitl-secrets      "$ASSET_ROOT/demo_hitl_service/.env"  # HITL service — HITL_INTERNAL_SECRET
secret_from_envfile langchain-secrets "$ASSET_ROOT/langchain_agent/.env"    # LangChain agent
inject_helix_api_key                                                        # Helix key from <agent>.json keyfile (patches langchain-secrets — must run after it exists)
mirror_google_api_key                                                       # BFF → langchain for Google/Gemini provider
mirror_groq_api_key                                                          # BFF → langchain for Groq provider
mirror_anthropic_api_key                                                    # BFF → langchain for Anthropic/Claude provider
secret_from_envfile gateway-secrets   "$ASSET_ROOT/demo_mcp_gateway/.env"   # MCP gateway
secret_from_envfile agent-secrets        "$ASSET_ROOT/demo_agent_service/.env" # Agent service
secret_from_envfile ping-gateway-secrets "$ASSET_ROOT/ping-gateway/.env"        # PingGateway (IG)
align_internal_secret                                                       # one internal secret across every consumer (must run after all four exist)

# Privilege proxy: ENV_PROXY_TOKEN from the gateway wizard, stored in
# ping-mcpgw/procyon/config/proxy-token.env — an ENV FILE (`ENV_PROXY_TOKEN=eyJ...`),
# not a bare JWT. Source it (same convention as secret_from_envfile above) rather
# than --from-file, which would store the literal string "ENV_PROXY_TOKEN=eyJ..."
# as the value instead of just the JWT.
if [ -f "$ASSET_ROOT/ping-mcpgw/procyon/config/proxy-token.env" ]; then
  # shellcheck disable=SC1090,SC1091
  ENV_PROXY_TOKEN="$(source "$ASSET_ROOT/ping-mcpgw/procyon/config/proxy-token.env" && echo "$ENV_PROXY_TOKEN")"
  # pingone.env carries the gateway's own OIDC client secret, so it belongs in
  # the Secret rather than a ConfigMap. It is only consulted in agentless
  # (self-hosted frontend) mode; the deployment mounts it optionally so a cluster
  # still running mesh mode does not fail to start without it. Kept as a single
  # --from-file blob because the deployment mounts it back as a whole file at
  # /var/lib/procyon/config/pingone.env, not individual env vars.
  mcpgw_secret_args=(--from-literal=ENV_PROXY_TOKEN="$ENV_PROXY_TOKEN")
  if [ -f "$ASSET_ROOT/ping-mcpgw/procyon/config/pingone.env" ]; then
    mcpgw_secret_args+=(--from-file=pingone.env="$ASSET_ROOT/ping-mcpgw/procyon/config/pingone.env")
  else
    warn "  ping-mcpgw/procyon/config/pingone.env not found — agentless mode will have no OIDC config"
  fi
  # Official Ping doc ("PingOne-Privilege-MCP-Gateway-Configuration.md") lists these
  # under "Required host configuration". Local docker-compose gets them for free via
  # a whole-tree mount; the K8s manifest mounts them explicitly at
  # /var/lib/procyon/ssl (see 75-ping-mcpgw-deployment.yaml), so they must ride in
  # this same secret. Optional, same reasoning as pingone.env above.
  if [ -f "$ASSET_ROOT/ping-mcpgw/procyon/ssl/mcpgw-cert.pem" ] && [ -f "$ASSET_ROOT/ping-mcpgw/procyon/ssl/mcpgw-key.pem" ]; then
    mcpgw_secret_args+=(--from-file=mcpgw-cert.pem="$ASSET_ROOT/ping-mcpgw/procyon/ssl/mcpgw-cert.pem")
    mcpgw_secret_args+=(--from-file=mcpgw-key.pem="$ASSET_ROOT/ping-mcpgw/procyon/ssl/mcpgw-key.pem")
  else
    warn "  ping-mcpgw/procyon/ssl/mcpgw-{cert,key}.pem not found — /var/lib/procyon/ssl will be empty in the pod"
  fi
  kubectl create secret generic ping-mcpgw-secrets \
    --namespace="$NS" \
    "${mcpgw_secret_args[@]}" \
    --dry-run=client -o yaml | kubectl apply -f -
  info "  ping-mcpgw-secrets applied (ENV_PROXY_TOKEN from ping-mcpgw/procyon/config/proxy-token.env)"
  override_privilege_urls_for_public_origin
else
  warn "  ping-mcpgw/procyon/config/proxy-token.env not found — skipping secret ping-mcpgw-secrets"
fi

# ── PingGateway config (ConfigMap from source files — single source of truth) ──
# ping-gateway/config/ and ping-gateway/scripts/groovy/ are the canonical
# config files; the ConfigMap is generated here so k8s and Docker use the
# same files (no duplication in 71-ping-gateway-deployment.yaml).
if [ -f "$ASSET_ROOT/ping-gateway/config/admin.json" ]; then
  info "Creating ping-gateway-config ConfigMap from source files..."
  kubectl create configmap ping-gateway-config \
    --namespace="$NS" \
    --from-file=admin.json="$ASSET_ROOT/ping-gateway/config/admin.json" \
    --from-file=config.json="$ASSET_ROOT/ping-gateway/config/config.json" \
    --from-file=mcp-tool-schemas.json="$ASSET_ROOT/mcp-tool-schemas.json" \
    --dry-run=client -o yaml | kubectl apply -f -
  kubectl create configmap ping-gateway-routes \
    --namespace="$NS" \
    --from-file="$ASSET_ROOT/ping-gateway/config/routes/" \
    --dry-run=client -o yaml | kubectl apply -f -
  kubectl create configmap ping-gateway-groovy \
    --namespace="$NS" \
    --from-file="$ASSET_ROOT/ping-gateway/scripts/groovy/" \
    --dry-run=client -o yaml | kubectl apply -f -
  info "  ping-gateway-config, ping-gateway-routes, ping-gateway-groovy applied."
else
  warn "ping-gateway/config/admin.json not found — skipping ping-gateway-config ConfigMap"
fi

# ── Monitoring: Prometheus scrape config + Grafana provisioning ───────────────
# Same trick as ping-gateway-config above: generate the ConfigMaps from the real
# files under monitoring/ so Docker Compose and Kubernetes read one copy and the
# two cannot drift.
if [ -f "$ASSET_ROOT/monitoring/prometheus.yml" ]; then
  info "Creating monitoring ConfigMaps from source files..."
  kubectl create configmap prometheus-config \
    --namespace="$NS" \
    --from-file=prometheus.yml="$ASSET_ROOT/monitoring/prometheus.yml" \
    --from-file=alerts.yml="$ASSET_ROOT/monitoring/alerts.yml" \
    --dry-run=client -o yaml | kubectl apply -f -
  kubectl create configmap grafana-datasources \
    --namespace="$NS" \
    --from-file="$ASSET_ROOT/monitoring/grafana/provisioning/datasources/" \
    --dry-run=client -o yaml | kubectl apply -f -
  kubectl create configmap grafana-dashboard-provider \
    --namespace="$NS" \
    --from-file="$ASSET_ROOT/monitoring/grafana/provisioning/dashboards/" \
    --dry-run=client -o yaml | kubectl apply -f -
  kubectl create configmap grafana-dashboards \
    --namespace="$NS" \
    --from-file="$ASSET_ROOT/monitoring/grafana/dashboards/" \
    --dry-run=client -o yaml | kubectl apply -f -
  info "  prometheus-config, grafana-datasources, grafana-dashboard-provider, grafana-dashboards applied."

  # Grafana admin login. GRAFANA_ADMIN_PASSWORD from the environment wins; the
  # fallback exists so a fresh cluster comes up loginable rather than broken.
  # Grafana is internet-facing via /grafana/, so change this for any deployment
  # that outlives a demo.
  grafana_user="${GRAFANA_ADMIN_USER:-admin}"
  grafana_pass="${GRAFANA_ADMIN_PASSWORD:-}"
  if [ -z "$grafana_pass" ]; then
    grafana_pass="ai-demo-grafana"
    warn "  GRAFANA_ADMIN_PASSWORD unset — using the default. Set it before any long-lived deployment."
  fi
  # PingOne SSO client secret for "Demo AI App - Grafana Login". Empty is fine:
  # Grafana still starts and the local admin form still works, so a stack
  # without it degrades to password login rather than breaking.
  grafana_oauth_secret="${GRAFANA_PINGONE_CLIENT_SECRET:-}"
  [ -n "$grafana_oauth_secret" ] \
    || warn "  GRAFANA_PINGONE_CLIENT_SECRET unset — PingOne SSO button will not work; local admin login still will."
  kubectl create secret generic grafana-secrets \
    --namespace="$NS" \
    --from-literal=GF_SECURITY_ADMIN_USER="$grafana_user" \
    --from-literal=GF_SECURITY_ADMIN_PASSWORD="$grafana_pass" \
    --from-literal=GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET="$grafana_oauth_secret" \
    --dry-run=client -o yaml | kubectl apply -f -
  info "  grafana-secrets applied (user: $grafana_user)."
else
  warn "monitoring/prometheus.yml not found — skipping monitoring ConfigMaps"
fi

# ── Restart deployments so already-running pods pick up what we just applied ──
# K8s does not hot-reload Secret/ConfigMap-sourced env vars into a running
# container — re-applying a secret above is a no-op for any pod that's already
# up. Root cause of the 2026-07-12 ping-gateway P1AZ outage: the secret got
# fixed but the pod kept running on its stale (pre-fix) environment, silently
# denying every request while reporting healthy. Restart every deployment that
# consumes a secret/configmap this script manages, so "rotate" always means
# rotate for the running pod too, not just for the next full deploy.
info "Restarting deployments to pick up refreshed secrets/configmaps..."
for dep in demo-api-server mcp-gateway mcp-server langchain-agent agent-service api-resource-server ping-gateway prometheus grafana; do
  if kubectl get deployment "$dep" --namespace="$NS" &>/dev/null; then
    kubectl rollout restart deployment "$dep" --namespace="$NS" >/dev/null
    info "  restarted $dep"
  else
    warn "  $dep not found in $NS — skipping restart (first-time bootstrap?)"
  fi
done

info "Done. Secrets are in namespace $NS."
