#!/bin/bash
# k8s/create-secrets.sh — create K8s secrets from local files
# Run once before deploy.sh, or re-run to rotate.
#
# Mirrors docker-compose's per-service env_file model: each service that has its
# own .env in the repo gets its own K8s secret, so MCP / langchain / agents
# receive the same credentials they do under `docker compose`.
#
# Quote handling: we SOURCE each .env (shell strips quotes) and emit
# --from-literal pairs. We deliberately do NOT use --from-env-file, which keeps
# surrounding quotes literally and corrupts secrets containing ~ . - etc.
#
# Prerequisites:
#   - demo_api_server/.env must exist (generated by bootstrap)
#   - certs/api.ping.demo+2.pem and certs/api.ping.demo+2-key.pem must exist
#   - (optional) <HELIX_AGENT_ID>.json keyfile (e.g. LLM2.json) for HELIX_API_KEY,
#     unless HELIX_API_KEY is already set in demo_api_server/.env
#
# Worktree fallback: .env files and certs are gitignored machine-local assets,
# so they do NOT travel to linked git worktrees. When this script runs from a
# worktree that lacks them, we transparently source the assets from the primary
# checkout (resolved via `git rev-parse --git-common-dir`) instead of failing.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NS="${K8S_NAMESPACE:-ai-demo}"

# Snapshot the caller's PUBLIC_APP_URL before any secret_from_envfile call can
# clobber it: secret_from_envfile does `set -o allexport; source $env_file`,
# which pollutes THIS script's own variable namespace with every key in each
# service .env — including PUBLIC_APP_URL from demo_api_server/.env (the
# local dev default). That silently overwrites a caller-supplied
# PUBLIC_APP_URL before override_redirect_uris_for_public_origin ever reads
# it, even when the caller exported it correctly. Broke live sign-in twice
# (2026-07-13) via the normal se-update-code.sh path, not just standalone runs.
CALLER_PUBLIC_APP_URL="${PUBLIC_APP_URL:-}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

info()    { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
die()     { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Resolve where the gitignored, machine-local assets actually live ─────────
# Prefer this checkout. If its .env is missing (typical when running from a git
# worktree, since gitignored files don't get checked out there), fall back to
# the primary checkout that owns the shared .git directory.
ASSET_ROOT="$REPO_ROOT"
if [ ! -f "$ASSET_ROOT/demo_api_server/.env" ]; then
  if git_common="$(git -C "$REPO_ROOT" rev-parse --git-common-dir 2>/dev/null)"; then
    case "$git_common" in
      /*) : ;;                                   # already absolute
      *)  git_common="$REPO_ROOT/$git_common" ;; # relativize to this checkout
    esac
    primary_root="$(cd "$(dirname "$git_common")" && pwd)"
    if [ "$primary_root" != "$REPO_ROOT" ] && [ -f "$primary_root/demo_api_server/.env" ]; then
      warn "demo_api_server/.env not found under $REPO_ROOT (likely a git worktree)."
      warn "Falling back to primary checkout for machine-local assets: $primary_root"
      ASSET_ROOT="$primary_root"
    fi
  fi
fi

# ── Preflight ─────────────────────────────────────────────────────────────────
[ -f "$ASSET_ROOT/demo_api_server/.env" ] || die "demo_api_server/.env not found. Run bootstrap first."
[ -f "$ASSET_ROOT/certs/api.ping.demo+2.pem" ]     || die "certs/api.ping.demo+2.pem not found. Run bootstrap first."
[ -f "$ASSET_ROOT/certs/api.ping.demo+2-key.pem" ] || die "certs/api.ping.demo+2-key.pem not found. Run bootstrap first."
[ -f "$ASSET_ROOT/certs/rootCA.pem" ]              || die "certs/rootCA.pem not found. Run ./run.sh once to copy the mkcert root CA."
kubectl get ns "$NS" &>/dev/null || die "Namespace $NS not found. Apply 01-namespace.yaml first."

# ── TLS secret from mkcert certs ─────────────────────────────────────────────
info "Creating tls-certs secret..."
# ca-bundle-with-mkcert.pem (system roots + mkcert root CA) lets the Python
# agents verify the BFF's mkcert cert via SSL_CERT_FILE without breaking
# external HTTPS — same bundle docker-compose mounts. Ship it when present.
CA_BUNDLE_ARG=()
if [ -f "$ASSET_ROOT/certs/ca-bundle-with-mkcert.pem" ]; then
  CA_BUNDLE_ARG=(--from-file=ca-bundle-with-mkcert.pem="$ASSET_ROOT/certs/ca-bundle-with-mkcert.pem")
fi
# Server-side apply: the CA bundle pushes the secret past the 256KB
# last-applied-configuration annotation limit of client-side apply.
kubectl create secret generic tls-certs \
  --namespace="$NS" \
  --from-file=tls.crt="$ASSET_ROOT/certs/api.ping.demo+2.pem" \
  --from-file=tls.key="$ASSET_ROOT/certs/api.ping.demo+2-key.pem" \
  --from-file=rootCA.pem="$ASSET_ROOT/certs/rootCA.pem" \
  "${CA_BUNDLE_ARG[@]}" \
  --dry-run=client -o yaml | kubectl apply --server-side --force-conflicts -f -
info "tls-certs secret applied."

# ── Helper: create one secret from a service's .env file ─────────────────────
# Usage: secret_from_envfile <secret-name> <path-to-.env>
secret_from_envfile() {
  local secret_name="$1" env_file="$2"
  if [ ! -f "$env_file" ]; then
    warn "  $env_file not found — skipping secret $secret_name"
    return
  fi

  # Collect declared variable names (ignore comments/blank lines)
  local keys=()
  while IFS= read -r k; do
    [ -n "$k" ] && keys+=("$k")
  done < <(grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$env_file" | sed 's/=$//' | sort -u)

  # Source the file so quote-wrapped values are unquoted by the shell, then read
  # each declared key's value back. Sourcing here (right before reading) keeps
  # values correct even when two .env files share a key name.
  set -o allexport
  # shellcheck disable=SC1090
  source "$env_file"
  set +o allexport

  local args=()
  for k in "${keys[@]}"; do
    local v="${!k:-}"
    [ -n "$v" ] && args+=(--from-literal="${k}=${v}")
  done

  if [ "${#args[@]}" -eq 0 ]; then
    warn "  $env_file has no usable keys — skipping $secret_name"
    return
  fi

  kubectl create secret generic "$secret_name" \
    --namespace="$NS" \
    "${args[@]}" \
    --dry-run=client -o yaml | kubectl apply -f -
  info "  $secret_name applied (${#args[@]} keys from $(basename "$(dirname "$env_file")")/.env)"
}

# ── Helix agent key: source from the gitignored <agent>.json keyfile ──────────
# HELIX_API_KEY is a secret, so it is NOT committed (it is absent from the
# configmap and usually from .env). Mirror what the BFF does locally
# (helixAgentKeyLoader.js): read it from <HELIX_AGENT_ID>.json in the repo root
# (ASSET_ROOT) / ~/Documents / ~/Downloads, and patch it into ai-demo-secrets.
# Skipped (leaving the .env value in place) when HELIX_API_KEY is already set in
# the BFF .env, and a no-op when no keyfile is present.
inject_helix_api_key() {
  local bff_env="$ASSET_ROOT/demo_api_server/.env"
  if grep -qE '^HELIX_API_KEY=.+' "$bff_env" 2>/dev/null; then
    info "  HELIX_API_KEY already set in .env — keyfile lookup skipped"
    # Still mirror into langchain-secrets when the BFF .env has the key but
    # langchain_agent/.env does not (typical on SE/AWS deploys).
    local helix_key
    helix_key=$(grep -E '^HELIX_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
    if [ -n "$helix_key" ]; then
      export HELIX_KEY="$helix_key"
      python3 - <<'PY' | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
import json, os
print(json.dumps({"stringData": {"HELIX_API_KEY": os.environ["HELIX_KEY"], "LANGCHAIN_LLM_PROVIDER": "helix"}}))
PY
      info "  HELIX_API_KEY mirrored into langchain-secrets from BFF .env"
    fi
    return
  fi

  # Agent id: .env override wins, else the committed configmap/configStore default.
  local agent="LLM2"
  local env_agent
  env_agent=$(grep -E '^HELIX_AGENT_ID=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  [ -n "$env_agent" ] && agent="$env_agent"

  local keyfile=""
  local f
  for f in "$ASSET_ROOT/${agent}.json" "$HOME/Documents/${agent}.json" "$HOME/Downloads/${agent}.json"; do
    [ -f "$f" ] && { keyfile="$f"; break; }
  done
  if [ -z "$keyfile" ]; then
    warn "  No HELIX_API_KEY in .env and no ${agent}.json keyfile found — Helix will be unconfigured in-cluster"
    return
  fi

  # Emit the patch JSON from python (keyValue read from the file, never passed on
  # the command line); empty output if the file has no keyValue.
  local patch
  patch=$(python3 - "$keyfile" <<'PY'
import json, sys
try:
    k = (json.load(open(sys.argv[1])).get('keyValue') or '').strip()
except Exception:
    k = ''
if k:
    print(json.dumps({'stringData': {'HELIX_API_KEY': k}}))
PY
)
  if [ -z "$patch" ]; then
    warn "  $(basename "$keyfile") has no keyValue — HELIX_API_KEY not set"
    return
  fi
  printf '%s' "$patch" | kubectl patch secret ai-demo-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  info "  HELIX_API_KEY injected into ai-demo-secrets from $(basename "$keyfile")"
  # LangChain agent mounts langchain-secrets (not ai-demo-secrets) — mirror the key
  # and default provider so in-cluster /run and WebSocket chat use Helix on SE/AWS.
  printf '%s' "$patch" | python3 -c "
import json, sys
p = json.load(sys.stdin)
p['stringData']['LANGCHAIN_LLM_PROVIDER'] = 'helix'
print(json.dumps(p))
" | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  info "  HELIX_API_KEY + LANGCHAIN_LLM_PROVIDER=helix mirrored into langchain-secrets"
}

# Mirror GOOGLE_API_KEY from the BFF .env into langchain-secrets so the agent
# can honor an explicit Google/Gemini provider selection in the LLM config UI.
mirror_google_api_key() {
  local bff_env="$ASSET_ROOT/demo_api_server/.env"
  local google_key
  google_key=$(grep -E '^GOOGLE_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  if [ -z "$google_key" ]; then
    google_key=$(grep -E '^GEMINI_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  fi
  if [ -z "$google_key" ]; then
    return
  fi
  export GOOGLE_KEY="$google_key"
  python3 - <<'PY' | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
import json, os
print(json.dumps({"stringData": {"GOOGLE_API_KEY": os.environ["GOOGLE_KEY"]}}))
PY
  info "  GOOGLE_API_KEY mirrored into langchain-secrets from BFF .env"
}

# Mirror GROQ_API_KEY from the BFF .env into langchain-secrets so the agent
# can honor an explicit Groq provider selection (GroqCloud, OpenAI-compatible).
mirror_groq_api_key() {
  local bff_env="$ASSET_ROOT/demo_api_server/.env"
  local groq_key
  groq_key=$(grep -E '^GROQ_API_KEY=.+' "$bff_env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  if [ -z "$groq_key" ]; then
    return
  fi
  export GROQ_KEY="$groq_key"
  python3 - <<'PY' | kubectl patch secret langchain-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
import json, os
print(json.dumps({"stringData": {"GROQ_API_KEY": os.environ["GROQ_KEY"]}}))
PY
  info "  GROQ_API_KEY mirrored into langchain-secrets from BFF .env"
}

# ── Cloud override: redirect URIs must match the public origin ───────────────
# The BFF .env carries the LOCAL redirect URIs (https://api.ping.demo:4000/...).
# Shipping them verbatim breaks sign-in on any public deployment: these keys are
# bootstrap-authoritative (env beats the runtime config store), so the BFF sends
# PingOne a redirect_uri that only resolves on the dev machine. When
# PUBLIC_APP_URL is set (required for SE/EKS deploys), derive them from it.
#
# If this script is run standalone (e.g. to patch a single secret) without
# PUBLIC_APP_URL exported, fall back to whatever origin is already live in the
# target namespace's configmap instead of silently reverting to local values —
# this happened on live (2026-07-13) and broke sign-in for every user.
override_redirect_uris_for_public_origin() {
  local origin="${CALLER_PUBLIC_APP_URL:-}"
  if [ -z "$origin" ]; then
    origin=$(kubectl get configmap ai-demo-config --namespace="$NS" -o jsonpath='{.data.PUBLIC_APP_URL}' 2>/dev/null || true)
    if [ -n "$origin" ]; then
      warn "  PUBLIC_APP_URL not set — falling back to existing configmap origin $origin"
    fi
  fi
  if [ -z "$origin" ]; then
    warn "  PUBLIC_APP_URL not set and no existing configmap origin found — PINGONE_*_REDIRECT_URI/PUBLIC_APP_URL shipped as-is from .env (local values; sign-in will break on a public deployment)"
    return
  fi
  origin="${origin%/}"
  local patch
  patch=$(printf '{"stringData":{"PUBLIC_APP_URL":"%s","PINGONE_PUBLIC_APP_URL":"%s","PINGONE_ADMIN_REDIRECT_URI":"%s/api/auth/oauth/callback","PINGONE_USER_REDIRECT_URI":"%s/api/auth/oauth/user/callback"}}' "$origin" "$origin" "$origin" "$origin")
  printf '%s' "$patch" | kubectl patch secret ai-demo-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  info "  PUBLIC_APP_URL/PINGONE_PUBLIC_APP_URL/PINGONE_ADMIN/USER_REDIRECT_URI overridden to match $origin"
}

# ── Demo service API key (apikey-dispatch path) ──────────────────────────────
# The gateway pulls DEMO_MORTGAGE_SERVICE_KEY / DEMO_INVEST_SERVICE_KEY from the
# BFF vault bridge and presents it to mortgage-service as X-API-Key. In-cluster
# the BFF has no vault password and no LMDB entry, so the bridge falls back to
# the committed default — while mortgage-service refuses to boot with that same
# default. Nothing else provisions the pair in k8s (ensure-service-keys.js is
# local-only), so a fresh deploy either crash-loops the backend or 401s every
# invest/mortgage chip ("backend rejected the service API key"). Single-source
# the key here: prefer the ensure-service-keys value from the repo-root .env,
# else mint one, then ship the SAME value to both sides (ai-demo-secrets for
# the BFF bridge, mortgage-secrets for the backend).
align_service_api_keys() {
  local key
  key=$(grep -E '^MORTGAGE_SERVICE_API_KEY=.+' "$ASSET_ROOT/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')
  case "$key" in
    ""|demo-mortgage-key-0000|mortgage-compose-dev-key)
      key="mortgage-$(openssl rand -hex 12)"
      warn "  MORTGAGE_SERVICE_API_KEY missing/default in repo-root .env — minted a deploy-local service key"
      ;;
  esac
  printf '{"stringData":{"DEMO_MORTGAGE_SERVICE_KEY":"%s","DEMO_INVEST_SERVICE_KEY":"%s"}}' "$key" "$key" \
    | kubectl patch secret ai-demo-secrets --namespace="$NS" --type merge --patch-file /dev/stdin >/dev/null
  kubectl create secret generic mortgage-secrets \
    --namespace="$NS" \
    --from-literal="MORTGAGE_SERVICE_API_KEY=${key}" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  info "  Service API key aligned across ai-demo-secrets (bridge) + mortgage-secrets (backend)"
}

# ── Per-service secrets (one per .env, mirroring docker-compose env_file) ─────
info "Creating per-service secrets from each service's .env..."
secret_from_envfile ai-demo-secrets   "$ASSET_ROOT/demo_api_server/.env"    # BFF (master)
override_redirect_uris_for_public_origin                                    # public origin beats local .env redirect URIs
align_service_api_keys                                                      # one key for the vault bridge AND the mortgage backend
inject_helix_api_key                                                        # Helix key from <agent>.json keyfile
mirror_google_api_key                                                       # BFF → langchain for Google/Gemini provider
mirror_groq_api_key                                                          # BFF → langchain for Groq provider
secret_from_envfile mcp-secrets       "$ASSET_ROOT/demo_mcp_server/.env"    # MCP server
secret_from_envfile langchain-secrets "$ASSET_ROOT/langchain_agent/.env"    # LangChain agent
secret_from_envfile gateway-secrets   "$ASSET_ROOT/demo_mcp_gateway/.env"   # MCP gateway
secret_from_envfile agent-secrets        "$ASSET_ROOT/demo_agent_service/.env" # Agent service
secret_from_envfile ping-gateway-secrets "$ASSET_ROOT/ping-gateway/.env"        # PingGateway (IG)

# ── PingGateway config (ConfigMap from source files — single source of truth) ──
# ping-gateway/config/ and ping-gateway/scripts/groovy/ are the canonical
# config files; the ConfigMap is generated here so k8s and Docker use the
# same files (no duplication in 71-ping-gateway-deployment.yaml).
if [ -f "$ASSET_ROOT/ping-gateway/config/admin.json" ]; then
  info "Creating ping-gateway-config ConfigMap from source files..."
  kubectl create configmap ping-gateway-config \
    --namespace="$NS" \
    --from-file=admin.json="$ASSET_ROOT/ping-gateway/config/admin.json" \
    --from-file=config.json="$ASSET_ROOT/ping-gateway/config/config.json" \
    --from-file=mcp-tool-schemas.json="$ASSET_ROOT/mcp-tool-schemas.json" \
    --dry-run=client -o yaml | kubectl apply -f -
  kubectl create configmap ping-gateway-routes \
    --namespace="$NS" \
    --from-file="$ASSET_ROOT/ping-gateway/config/routes/" \
    --dry-run=client -o yaml | kubectl apply -f -
  kubectl create configmap ping-gateway-groovy \
    --namespace="$NS" \
    --from-file="$ASSET_ROOT/ping-gateway/scripts/groovy/" \
    --dry-run=client -o yaml | kubectl apply -f -
  info "  ping-gateway-config, ping-gateway-routes, ping-gateway-groovy applied."
else
  warn "ping-gateway/config/admin.json not found — skipping ping-gateway-config ConfigMap"
fi

# ── Restart deployments so already-running pods pick up what we just applied ──
# K8s does not hot-reload Secret/ConfigMap-sourced env vars into a running
# container — re-applying a secret above is a no-op for any pod that's already
# up. Root cause of the 2026-07-12 ping-gateway P1AZ outage: the secret got
# fixed but the pod kept running on its stale (pre-fix) environment, silently
# denying every request while reporting healthy. Restart every deployment that
# consumes a secret/configmap this script manages, so "rotate" always means
# rotate for the running pod too, not just for the next full deploy.
info "Restarting deployments to pick up refreshed secrets/configmaps..."
for dep in demo-api-server mcp-gateway mcp-server langchain-agent agent-service mortgage-service ping-gateway; do
  if kubectl get deployment "$dep" --namespace="$NS" &>/dev/null; then
    kubectl rollout restart deployment "$dep" --namespace="$NS" >/dev/null
    info "  restarted $dep"
  else
    warn "  $dep not found in $NS — skipping restart (first-time bootstrap?)"
  fi
done

info "Done. Secrets are in namespace $NS."
