"""
Environment variable validation for langchain_agent.

Validates that all required OAuth and configuration variables are present,
providing clear error messages and recovery instructions when missing.
"""

import logging
import os
import sys
from typing import Dict, List, Tuple

logger = logging.getLogger(__name__)


class EnvValidationError(Exception):
    """Raised when required environment variables are missing."""
    pass


class EnvironmentValidator:
    """Validates required environment variables at startup."""

    # Required OAuth credentials (at least one pair must be present)
    OAUTH_CREDENTIAL_PAIRS = [
        ('PINGONE_USER_CLIENT_ID', 'PINGONE_USER_CLIENT_SECRET'),
        ('AGENT_CLIENT_ID', 'AGENT_CLIENT_SECRET'),
    ]

    # Optional LLM provider credentials (at least one LLM must be configured).
    # Keys must match what agent/llm_factory.py actually supports — an entry
    # here that the factory can't build (previously 'ollama') is misleading.
    LLM_PROVIDER_VARS = {
        'helix': ['HELIX_BASE_URL', 'HELIX_API_KEY', 'HELIX_ENVIRONMENT_ID'],
        'anthropic': ['ANTHROPIC_API_KEY'],
        'anthropic-lmstudio': ['LMSTUDIO_BASE_URL'],
        'lmstudio': ['LMSTUDIO_BASE_URL'],
        'llamacpp': ['LLAMACPP_BASE_URL'],
    }

    # Providers agent/llm_factory.get_llm() can actually construct. 'none'
    # (or empty) means heuristic-only routing with no LLM.
    SUPPORTED_LLM_PROVIDERS = frozenset({
        'none', 'helix', 'anthropic', 'anthropic-lmstudio', 'lmstudio', 'llamacpp',
    })

    # Optional MCP configuration
    MCP_VARS = ['MCP_SERVER_URL', 'MCP_TRANSPORT']

    # Optional session configuration
    SESSION_VARS = ['SESSION_TIMEOUT_MINUTES', 'LANGCHAIN_MAX_CONTEXT_TOKENS']

    @staticmethod
    def get_env(key: str, default: str = '') -> str:
        """Get environment variable with optional default."""
        return os.environ.get(key, default)

    @classmethod
    def validate_oauth_credentials(cls) -> Tuple[bool, str]:
        """
        Validate that at least one OAuth credential pair is present.

        Returns:
            (is_valid, error_message)
        """
        for client_id_key, secret_key in cls.OAUTH_CREDENTIAL_PAIRS:
            client_id = cls.get_env(client_id_key)
            secret = cls.get_env(secret_key)

            if client_id and secret:
                # Found a valid pair
                return True, ''

        # No valid credentials found
        missing = []
        for client_id_key, secret_key in cls.OAUTH_CREDENTIAL_PAIRS:
            missing.append(f"  - {client_id_key} + {secret_key}")

        error_msg = (
            'No pre-provisioned OAuth client credentials found.\n\n'
            'LangChain agent requires one of the following credential pairs:\n' +
            '\n'.join(missing) +
            '\n\n'
            'To fix:\n'
            '  1. Run: npm run pingone:bootstrap (if not already done)\n'
            '  2. This auto-generates all required .env files including langchain_agent/.env\n'
            '  3. Restart the container: docker-compose restart langchain-agent\n\n'
            'If bootstrap is already done, check that langchain_agent/.env has the required credentials.'
        )
        return False, error_msg

    @classmethod
    def validate_core_config(cls) -> Tuple[bool, str]:
        """
        Validate that core PingOne configuration is present.

        Returns:
            (is_valid, error_message)
        """
        required_vars = [
            'PINGONE_BASE_URL',
            'PINGONE_TOKEN_ENDPOINT',
            'PINGONE_AUTHORIZATION_ENDPOINT',
        ]

        missing = []
        for var in required_vars:
            if not cls.get_env(var):
                missing.append(var)

        if missing:
            error_msg = (
                f'Missing required PingOne configuration: {", ".join(missing)}\n\n'
                'These are automatically generated by: npm run pingone:bootstrap\n'
                'Check that demo_api_server/scripts/refresh-service-envs.js is up-to-date.'
            )
            return False, error_msg

        return True, ''

    @classmethod
    def warn_unsupported_llm_provider(cls) -> None:
        """
        F11: warn (do not crash) when LANGCHAIN_LLM_PROVIDER names a provider
        the LLM factory can't build. An unknown provider silently degrades to
        no-LLM (heuristic-only) routing, which is easy to miss at boot.
        """
        raw = cls.get_env('LANGCHAIN_LLM_PROVIDER').strip()
        if not raw:
            return  # unset → factory defaults to 'none' (heuristic routing)
        if raw.lower() not in cls.SUPPORTED_LLM_PROVIDERS:
            logger.warning(
                "⚠️ LANGCHAIN_LLM_PROVIDER=%r is not supported — the agent will "
                "fall back to no-LLM (heuristic-only) routing. Supported: %s",
                raw, ", ".join(sorted(cls.SUPPORTED_LLM_PROVIDERS)),
            )

    @classmethod
    def warn_missing_agent_audience(cls) -> None:
        """
        F12: warn at boot when no token-validation audience is configured.
        Without PINGONE_RESOURCE_LANGCHAIN_AGENT_URI (or LANGCHAIN_ACCEPTED_
        AUDIENCES) the agent boots 'healthy' but the token validator raises on
        the FIRST chat, so every session 500s. Surfacing it at startup makes
        the misconfiguration visible immediately. Warn (not crash) to avoid
        breaking dev before the dedicated PingOne resource is provisioned.
        """
        if not (cls.get_env('PINGONE_RESOURCE_LANGCHAIN_AGENT_URI')
                or cls.get_env('LANGCHAIN_ACCEPTED_AUDIENCES')):
            logger.warning(
                "⚠️ No token-validation audience configured "
                "(PINGONE_RESOURCE_LANGCHAIN_AGENT_URI / "
                "LANGCHAIN_ACCEPTED_AUDIENCES both unset). The agent will boot "
                "but token validation will fail on the first chat session. "
                "Set PINGONE_RESOURCE_LANGCHAIN_AGENT_URI to fix."
            )

    @classmethod
    def validate_all(cls) -> None:
        """
        Validate all required environment variables.

        Raises:
            EnvValidationError if required vars are missing
        """
        # Check OAuth credentials first (most common failure)
        is_valid, error_msg = cls.validate_oauth_credentials()
        if not is_valid:
            raise EnvValidationError(error_msg)

        # Check core config
        is_valid, error_msg = cls.validate_core_config()
        if not is_valid:
            raise EnvValidationError(error_msg)


def validate_environment() -> None:
    """
    Validate environment at application startup.

    Should be called early in the application initialization,
    before any OAuth manager or MCP components are created.

    Raises:
        EnvValidationError with user-friendly error message on failure
    """
    try:
        EnvironmentValidator.validate_all()
        # Non-fatal startup checks (F11/F12): warn loudly rather than crash so
        # misconfiguration is visible at boot, not at first chat.
        EnvironmentValidator.warn_unsupported_llm_provider()
        EnvironmentValidator.warn_missing_agent_audience()
    except EnvValidationError as e:
        print(f'\n❌ Environment Validation Error:\n\n{str(e)}\n', file=sys.stderr)
        sys.exit(1)
