apiVersion: v2
appVersion: "1.0"
description: Privilege proxy gateway with OpenSearch and PingOne MCP servers
keywords:
- mcp
- gateway
- procyon
- opensearch
- pingone
maintainers:
- name: cjmuir
name: privgateway
type: application
version: 0.1.0
