{{- if .Values.mcpgw.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mcpgw-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    app: mcpgw
    {{- include "privgateway.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mcpgw.ssl.storage }}
{{- end }}
