#!/bin/bash
#
# Pre-startup environment validation for langchain_agent
#
# Checks that required OAuth credentials are present before attempting to start
# the Python application. Provides clear error messages if validation fails.
#
# Usage:
#   ./scripts/validate-startup-env.sh
#
# Exit codes:
#   0 = all validations passed
#   1 = validation failed (prints error message to stderr)

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if at least one OAuth credential pair is present
check_oauth_credentials() {
    local pingone_user_id="${PINGONE_USER_CLIENT_ID:-}"
    local pingone_user_secret="${PINGONE_USER_CLIENT_SECRET:-}"
    local agent_id="${AGENT_CLIENT_ID:-}"
    local agent_secret="${AGENT_CLIENT_SECRET:-}"

    if [[ -n "$pingone_user_id" && -n "$pingone_user_secret" ]]; then
        echo -e "${GREEN}✓${NC} OAuth credentials found: PINGONE_USER_CLIENT_ID"
        return 0
    fi

    if [[ -n "$agent_id" && -n "$agent_secret" ]]; then
        echo -e "${GREEN}✓${NC} OAuth credentials found: AGENT_CLIENT_ID"
        return 0
    fi

    # No valid credentials found
    cat >&2 <<'EOF'

❌ Pre-startup validation failed: Missing OAuth credentials

LangChain agent requires one of these credential pairs:
  • PINGONE_USER_CLIENT_ID + PINGONE_USER_CLIENT_SECRET
  • AGENT_CLIENT_ID + AGENT_CLIENT_SECRET

Diagnosis:
  1. Check if langchain_agent/.env file exists:
     ls -la langchain_agent/.env

  2. If .env is missing, run bootstrap to generate credentials:
     npm run pingone:bootstrap

  3. If .env exists but is empty/wrong, check the env refresh script:
     grep -A 5 "langchain_agent/.env" demo_api_server/scripts/refresh-service-envs.js

  4. If running in Docker, restart the container:
     docker-compose restart langchain-agent

  5. Check startup logs for details:
     docker logs ai-demo-langchain-agent | grep -i error

Reference: docs/ENV_VALIDATION_SCHEMA.md

EOF
    return 1
}

# Check core PingOne configuration
check_pingone_config() {
    local base_url="${PINGONE_BASE_URL:-}"
    local token_endpoint="${PINGONE_TOKEN_ENDPOINT:-}"

    if [[ -z "$base_url" || -z "$token_endpoint" ]]; then
        cat >&2 <<'EOF'

❌ Pre-startup validation failed: Missing PingOne configuration

Required PingOne variables are not set:
  • PINGONE_BASE_URL
  • PINGONE_TOKEN_ENDPOINT

These should be auto-generated by: npm run pingone:bootstrap

Fix: Run bootstrap to regenerate all .env files

EOF
        return 1
    fi

    echo -e "${GREEN}✓${NC} PingOne configuration found (PINGONE_BASE_URL)"
    return 0
}

# Main validation
main() {
    echo "Validating environment for langchain_agent startup..."
    echo

    # Run checks
    if ! check_oauth_credentials; then
        return 1
    fi

    if ! check_pingone_config; then
        return 1
    fi

    echo
    echo -e "${GREEN}✓${NC} All pre-startup validations passed"
    return 0
}

# Execute
main "$@"
