{{- if .Values.opensearch.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-opensearch-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: opensearch
    {{- include "privgateway.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.opensearch.storage }}
{{- end }}
