apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-instrument
  namespace: {{ .Release.Namespace }}
  labels:
    app: ai-demo
data:
  otel-instrument.js: |
{{ .Files.Get "files/otel-instrument.js" | indent 4 }}
