apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentless-mcpgw.name" . }}-oidc-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agentless-mcpgw.labels" . | nindent 4 }}
type: Opaque
stringData:
  pingone.env: |
    SERVER_URL={{ .Values.oidc.serverUrl }}
    OIDC_CLIENT_ID={{ .Values.oidc.clientId }}
    OIDC_CLIENT_SECRET={{ .Values.oidc.clientSecret }}
    OIDC_AUTH_URL={{ .Values.oidc.authUrl }}
    OIDC_TOKEN_URL={{ .Values.oidc.tokenUrl }}
    OIDC_USER_URL={{ .Values.oidc.userUrl }}
    OIDC_SCOPES={{ .Values.oidc.scopes }}
