apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentless-mcpgw.name" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agentless-mcpgw.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENV_PROXY_TOKEN: {{ .Values.proxyToken | quote }}
