import React, { useState, useCallback, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import SetupWizard from './SetupWizard';
import SetupStepHelix from './SetupStepHelix';
import SetupStepVerify from './SetupStepVerify';
import apiClient from '../services/apiClient';
import './SetupPage.css';

const STEPS = [
  { n: 1, label: 'PingOne Credentials' },
  { n: 2, label: 'Helix / LLM' },
  { n: 3, label: 'Bootstrap PingOne' },
  { n: 4, label: 'Verify & Go' },
];

function stepStatus(n, activeStep, completedSteps) {
  if (completedSteps.has(n)) return 'done';
  if (n === activeStep) return 'active';
  return 'pending';
}

function isUnlocked(n, completedSteps) {
  if (completedSteps.size === 4) return true;
  const maxDone = Math.max(0, ...Array.from(completedSteps));
  return n <= maxDone + 1;
}

function BadgeLabel({ status, n }) {
  if (status === 'done') return '✅';
  return String(n);
}

export default function SetupPage() {
  const [activeStep, setActiveStep] = useState(1);
  const [completedSteps, setCompletedSteps] = useState(new Set());
  const [loadingState, setLoadingState] = useState(true);
  // Shared PingOne credentials — entered in Step 1, reused by the Step 3
  // bootstrap run (both render their own SetupWizard instance).
  const [creds, setCreds] = useState({
    envId: '',
    workerClientId: '',
    workerClientSecret: '',
    region: 'com',
    publicAppUrl: window.location.origin.replace(':3000', ':4000'),
    stepUpAcrValue: 'Multi_Factor',
  });
  const navigate = useNavigate();

  useEffect(() => {
    (async () => {
      try {
        const { data } = await apiClient.get('/api/langchain/config/status');
        const done = new Set();
        if (data?.pingone_environment_id) done.add(1);
        if (data?.helix_base_url && data?.helix_api_key_set) done.add(2);
        try {
          const probe = await apiClient.get('/api/admin/setup/management-probe');
          if (probe.data?.ok) done.add(3);
        } catch { }
        setCompletedSteps(done);
        for (let n = 1; n <= 4; n++) {
          if (!done.has(n)) { setActiveStep(n); break; }
          if (n === 4) setActiveStep(4);
        }
      } catch { }
      finally { setLoadingState(false); }
    })();
  }, []);

  const markDone = useCallback((n) => {
    setCompletedSteps(prev => {
      const next = new Set(prev);
      next.add(n);
      return next;
    });
    if (n < 4) setActiveStep(n + 1);
  }, []);

  const handleEnvDownload = useCallback(async () => {
    try {
      const { data: cfg } = await apiClient.get('/api/langchain/config/status');
      const lines = [
        '# PingOne Configuration - Generated by Setup Wizard',
        `PINGONE_ENVIRONMENT_ID=${cfg?.pingone_environment_id || ''}`,
        `PINGONE_REGION=${cfg?.pingone_region || 'com'}`,
        '',
        '# Helix LLM - Generated by Setup Wizard',
        `HELIX_BASE_URL=${cfg?.helix_base_url || ''}`,
        `HELIX_API_KEY=<stored-in-configstore>  # TODO: paste your keyValue here`,
        `HELIX_ENVIRONMENT_ID=${cfg?.helix_environment_id || ''}`,
        `HELIX_AGENT_ID=${cfg?.helix_agent_id || ''}`,
        `HELIX_PROMPT_FIELD_ID=${cfg?.helix_prompt_field_id || ''}`,
      ].join('\n');

      const blob = new Blob([lines], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'demo_api_server.env';
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('[SetupPage] .env download failed:', err.message);
    }
  }, []);

  if (loadingState) return <div style={{ padding: '2rem', fontSize: '0.9rem', color: '#6b7280' }}>Loading setup state…</div>;

  return (
    <div className="setup-page">
      <aside className="setup-sidebar">
        <div className="setup-sidebar-title">Setup Steps</div>
        {STEPS.map(({ n, label }) => {
          const status = stepStatus(n, activeStep, completedSteps);
          const unlocked = isUnlocked(n, completedSteps);
          return (
            <button
              key={n}
              className={`setup-step-item ${status}${!unlocked ? ' locked' : ''}`}
              onClick={() => unlocked && setActiveStep(n)}
              disabled={!unlocked}
            >
              <span className={`setup-step-badge ${status}`}>
                <BadgeLabel status={status} n={n} />
              </span>
              {n}. {label}
            </button>
          );
        })}
        <div className="setup-sidebar-footer">
          <button className="setup-download-btn" onClick={handleEnvDownload}>
            Download .env
          </button>
        </div>
      </aside>

      <main className="setup-main">
        {activeStep === 1 && (
          <>
            <div className="setup-step-title">Step 1 — PingOne Credentials</div>
            <div className="setup-step-subtitle">Enter your PingOne worker app credentials to enable Management API access.</div>
            <SetupWizard embeddedMode creds={creds} onCredsChange={setCreds} onCredentialsValid={() => markDone(1)} />
          </>
        )}

        {activeStep === 2 && (
          <>
            <div className="setup-step-title">Step 2 — Helix / LLM Setup</div>
            <div className="setup-step-subtitle">Connect the Helix AI agent that powers natural language routing in the demo.</div>
            <SetupStepHelix onComplete={() => markDone(2)} />
          </>
        )}

        {activeStep === 3 && (
          <>
            <div className="setup-step-title">Step 3 — Bootstrap PingOne</div>
            <div className="setup-step-subtitle">Provision apps, resource servers, scopes, and demo users in your PingOne environment.</div>
            <SetupWizard embeddedMode bootstrapOnly creds={creds} onCredsChange={setCreds} onBootstrapComplete={() => markDone(3)} />
          </>
        )}

        {activeStep === 4 && (
          <>
            <div className="setup-step-title">Step 4 — Verify &amp; Go</div>
            <div className="setup-step-subtitle">Run health checks to confirm all services are running and configuration is complete.</div>
            <SetupStepVerify onEnvDownload={handleEnvDownload} />
          </>
        )}
      </main>
    </div>
  );
}
